# Auto-generated by deploy-lxc.sh on Wed, Mar  4, 2026  8:17:43 PM

# Proxmox Connection
proxmox_api_url      = "https://pve01.knowledgeondemand.net:8006"
proxmox_api_token    = "terraform@pve!provider=0e837666-70fe-46c1-854b-9a11e818f45f"
proxmox_ssh_user     = "root"
proxmox_ssh_password = "REDACTED"
proxmox_node         = ""
proxmox_pool         = ""

# LXC Container Configuration
lxc_vmid      = 201
lxc_hostname  = "build-vm"
lxc_cores     = 2
lxc_memory    = 4096
lxc_swap      = 512
lxc_disk_size = 50
lxc_storage   = "local-lvm"
lxc_tags      = ["build", "docker", "management"]

# Template
template_storage      = "cephfs"
lxc_template_filename = "debian-12-standard_12.12-1_amd64.tar.zst"

# Network
network_bridge  = "vmbr0"
vlan_id         = 3
lxc_ip_address  = "10.83.3.191/24"
lxc_gateway     = "10.83.3.1"
lxc_mac_address = ""

# DNS
dns_domain  = "knowledgeondemand.net"
dns_servers = ["8.8.8.8", "8.8.4.4"]

# Auth
lxc_root_password = "REDACTED"
ssh_public_keys   = []

# SSH User (created via pct exec after deployment)
ssh_user          = "deploy"
ssh_user_password = "REDACTED"
ssh_user_groups   = "sudo,docker"
