#ENC[AES256_GCM,data:JNdGNI3VB6XLPVKsghwGMv27/JPO7PxqSR3i8TB4K+Iw6UqZ/bReQrwXAa7hDQc+6V1HQHg2fV9rlsrISTvuDRHD0W05lGCJAwM=,iv:6GDjxAtJ9HbHsLFxrRpfBqsH5rPVmLfKGmbIO4bOb7c=,tag:SpxgGcWrAzdNyOrNk325pg==,type:comment]
#ENC[AES256_GCM,data:J/7MIKLiSoWLqCS5ujm+sLPWWixZIydt+Zgj+X3D2hBX1VVsEHqoprJxQM7zj8gJ4mqHM1BfT8wDiA==,iv:gbvLdYcEF1/pIvTaRi2teX8EbEhpf9tAKzUyCwpJ3k0=,tag:mDLH8AGZ3lcFYgUnxUGEVw==,type:comment]
#ENC[AES256_GCM,data:iZTp11g9SNrGTOGJf5DGk0djTj5z1n3uWkwIDtR6QbqWv8WdTvhhfaQpDQUC/Trsr5K/BrxiG7tN580=,iv:V8N1xT1DH8kix2awmBrg/MnMnvntLBx5wcIt1q9stn4=,tag:0RD720gzjlzQAA3j/KIdZg==,type:comment]
#
#ENC[AES256_GCM,data:7NPXhHi5Rse1UZsY6BXldOZ++pZMccPBK2Uz0VS8WGT20bfmNBmr+/cl/lMJU46NOxZrZHKGH4RiqIhxGDfR2fkp1A==,iv:63d4YC4yVkT7F8tyrWZ+r7aR3H88CVJIhvTXHba/iCU=,tag:6pj2T0co/yDjHiY30z69JA==,type:comment]
apiVersion: ENC[AES256_GCM,data:5/Y=,iv:1+xggHuB4KSy/D0Y5P4s+7LHVN6h053OexoO0GoaISQ=,tag:MKxka4TG7YH83S1zRqGQ6g==,type:str]
kind: ENC[AES256_GCM,data:p6fCT7fJ,iv:AknPhaf17TgzazS/KK08qHGgOvpzHrMe95DxSGhvCNQ=,tag:GWDmRSwFJSs0wmvExx0I5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RdzOojGhO5sODv1yvFk=,iv:bt8qJVMR4wBMJz6t7FxfXMy2k4OhNN6LhyrwEF7ZTBw=,tag:27rZgFsrp8yFpgylTvflHA==,type:str]
    namespace: ENC[AES256_GCM,data:DV4zi3ONoZo=,iv:Z5QdCxYZnrDqro+T5unBmCi/CpRDYO7LrzJaadJiz+k=,tag:8TB+8cFPrGDOHAB4dXLAEw==,type:str]
type: ENC[AES256_GCM,data:sa1nCrgb,iv:uxicFG7xpZrBX5xQFt2oUxj3SisCcv4xTPI9B/s9Vck=,tag:ejvKIBVzrMdZzWKWrQFJag==,type:str]
stringData:
    #ENC[AES256_GCM,data:i7g/i+6fShfHvSN8plCsXNxUepN1bPF3yKvMhn3OYqv2p3XR4SdJ84KNefDlaW9kJ8sXKHS3NLnjZYkLxMxeGI1PBUDvfTVpLbyufpUJhnNGIiRSrVk=,iv:4gGsQc9mQoG8/tLtXcSgrjYJ5wKQikCeU08ixfZvW54=,tag:no0oY+U/6PU+Dgs/8hO/zQ==,type:comment]
    userID: ENC[AES256_GCM,data:2D56Es61suurfw==,iv:x6Z8NtIHltj9B7mHdhiUtxbqexHHc+5afIWlFQIqh5k=,tag:eRNnSWcwr+pNj1r1tM+beA==,type:str]
    userKey: ENC[AES256_GCM,data:1Fp71OBKP7R2WhYexKHPwuajF8vsdfvMWmOSUSNo9nroUx/DKAY1Dg==,iv:vW6g1Lyh5dxjWhCkOmrgG6eykY/dHoEi5nzYPffXuDU=,tag:5nMSbq9oSjp+/uZcnrq9eA==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxckFCT25TeVdGdi9rRllE
            Q0JpenQ3M0tqUEdZSkNlRjREN0g1S0hreFFvCk91YUE4MXlZelRrNTh6ZDBaQkRi
            bG9Udjl2TlFaNHpBSXhHOElzWDRLTm8KLS0tIG9IRHgvOWFNUjFIVTdpekc5eHhC
            MGdYQUkvQUFxRHpQeU9zdERiNnJudkUKctZgho76hTA3SmhziUWGZvf0npFzvxbQ
            tTGQU5UQ7M5Vnu0Vzt3DeEHeQ8jAx9r6VRw0q8jIL2jOI3L89WImOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T21:34:04Z"
    mac: ENC[AES256_GCM,data:Hv2Pg4lJGfKDMXNyjHcNnm+WCuIbbnxASHs2owAnpdgYtTBUEQ8MsSDdDyFuYDwekjBp94wJJ4HEhPKntcRt8FLIFKDdyJJVMkvFWZKtr+GWp7Q7tX1jxknIfXuP1MSV+YqwbTahUN35ZQVySi9zqoV8Tz1LhgCwgDLPxYI7pqI=,iv:edzZqX4sc+/OMKXKYopZVB4STA7dc3EiS76WcQ/WagU=,tag:dRVyySsNF9jVG78LKTtkfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
