apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQU53NjJNd2pzUHk1ZFdGOVFYQ1FaV1F3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakF6TURVd01qVTNOVE5hRncwek5qQXpNREl3TWpVMwpOVE5hTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVQza2ZlNmxtb0d5M0hxVW8zRHFwVW9waHFyYkFiakdpNm1sKyt6SkFFMkZ2WC9mMzJLelZuS01nREoKMG5tOCt4R3ppck9LOUQ2RldQUkhvUXJ1Q0lNVW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGSTBqMVh6aXZCdEJtNXZqczRMTVpJRklSdU5iTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEcjVxdVUKcmc1eHdqMWtZTTR5Mm1aeGJwQnpLa3hJQndSbE9EaEtQZTcrYVFJZ2JESUF1UFFLMG8wV0RXN1VNc25nMW01NgpnTGs4MnZHZmR1SjFYNkEwanl3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://talos-CleanRoom-master-01.knowledgeondemand.net:6443
  name: proxmox-CleanRoom-cluster
contexts:
- context:
    cluster: proxmox-CleanRoom-cluster
    namespace: default
    user: admin@proxmox-CleanRoom-cluster
  name: admin@proxmox-CleanRoom-cluster
current-context: admin@proxmox-CleanRoom-cluster
kind: Config
users:
- name: admin@proxmox-CleanRoom-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVN1Z0F3SUJBZ0lSQUtCcEZ0eWJPZEEvcm0rOTBnNFJFY1l3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakF6TURVd016QXhNelZhRncweU56QXpNRFV3TXpBeApORFZhTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQlBaWjBmOWJwcEd4d2pEdS9mRXEzYXJQalFRVmwveDkKRk5Ubm9SYzRDd2dWaEFmTU8rRHdPZlk5MHFFSllTSkZPdmIrdEJVcmplczZxZVhmK2Q1elVKV2pTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlNOCkk5Vjg0cndiUVp1YjQ3T0N6R1NCU0Viald6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF0cE9rcC9LV0hndmEKNTFNNVBrcXI0SzJsY0NUeDU1NnFPZGh2MVMrVm5zZ0NJSGtYMzA3TXlLc08zREUyaEkvYmRBbFNrQ1JxTXpTRAoyNkFWSFIvWkFLMHQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1lMnVPZ3Zsb1hSSkZpS1dIUzlidFZpRytvVGh0cktuWmxMVERSSGw0T1ZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOWxuUi8xdW1rYkhDTU83OThTcmRxcytOQkJXWC9IMFUxT2VoRnpnTENCV0VCOHc3NFBBNQo5ajNTb1FsaElrVTY5djYwRlN1TjZ6cXA1ZC81M25OUWxRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
