apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUo1WGxLTXlVSk9zb3pFOTBML3NIMEF3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEwTURreE1qSTBNVFJhRncwek5qQTBNRFl4TWpJMApNVFJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRXMkhadzhtZDRxR1VFeHQycm84Nm9WUC9UMy8veWJhclZpL1R3OUxmejJ3bk10N05XNk0zd3RySVkKQUtGTU9ZSTIxV2RodHpZcFZxZC9od1JrRDNvZG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGQXBXMnZaQWNOMFRXWFdhRzdLUE9YQlE1ayt6TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUhHNkdvQk4Kb1MvVStiSTByVDVXRURHYzFjdFFwQmRRTzFLZkpXa2M1dUxzQWlFQWltVU1mZ0kvOE4vZnQvazZMeUtGbExSZwp5T1R2M21lVnhpVENCTml5R2JVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://talos-CleanRoom-master-01.knowledgeondemand.net:6443
  name: proxmox-CleanRoom-cluster
contexts:
- context:
    cluster: proxmox-CleanRoom-cluster
    namespace: default
    user: admin@proxmox-CleanRoom-cluster
  name: admin@proxmox-CleanRoom-cluster
current-context: admin@proxmox-CleanRoom-cluster
kind: Config
users:
- name: admin@proxmox-CleanRoom-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoRENDQVN1Z0F3SUJBZ0lSQUl0KzdnYU45RDlHckNvNkUraXFnOG93Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEwTURreE1qSTNNemxhRncweU56QTBNRGt4TWpJMwpORGxhTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkRzYSsrckJoMlJYQlRYc21PK0w4eWRHbEU4Wi9Xd24KL3h3ZWlYQlcwMVNDdlM1dnk0WkF1RjIzbmFoTVNiaHlIcTVSVC8rRkZsUnU5dktmMVgwSjIvYWpTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlFLClZ0cjJRSERkRTFsMW1odXlqemx3VU9aUHN6QUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQXVBdlgxMmdqclk5QVEKcDBVU3ZYK3lUcEtYRWg1QUczUkgvaUJobkJRbXhBSWdITTlQc25sZ0duUjFSSCs2RTlIMGFQQXY1dE5DM0d2UApVdWhnam1vUmpKRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBLQXhqUmZMZHZRVWxRY0Z0T0RuOUxzVkNTTU1DZlV6VFBTM2Y2WUJyZzRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFT3hyNzZzR0haRmNGTmV5WTc0dnpKMGFVVHhuOWJDZi9IQjZKY0ZiVFZJSzlMbS9MaGtDNApYYmVkcUV4SnVISWVybEZQLzRVV1ZHNzI4cC9WZlFuYjlnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
