apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVRDZ0F3SUJBZ0lSQUpnaFByblVsVUJITmd0cnJWekhSejh3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEwTURZd01URTJNVE5hRncwek5qQTBNRE13TVRFMgpNVE5hTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVQyVXBEbUpnMmQwa1U4MHhtNkpiMHdwbHdBNmxEZzhzTHp1Q3BGVXZTRHdURzV1WUlKek12c2IrczAKUi9Jd20wZ2RLdURndXNMZEhkKzFJSkFDWVQ0SW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGRnJCY0FNc2JGeWdERTZNOTBEbjZBOVJMRkh3TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNCN011aXkKN0pvSlRsbWZoRU02Uno4Y05NV3c5Q1JRcVk1Wk4vbC9MRUpvQWlCOTVVTWxsRzRUSUorSHlUdDQzWWg3T3lvNgplVzRCcUdibzlZTkx2ZlJ4QkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://talos-CleanRoom-master-01.knowledgeondemand.net:6443
  name: proxmox-CleanRoom-cluster
contexts:
- context:
    cluster: proxmox-CleanRoom-cluster
    namespace: default
    user: admin@proxmox-CleanRoom-cluster
  name: admin@proxmox-CleanRoom-cluster
current-context: admin@proxmox-CleanRoom-cluster
kind: Config
users:
- name: admin@proxmox-CleanRoom-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVN1Z0F3SUJBZ0lSQUtsZEFjb3RRMzN0aWo0aHVEdzFqUFl3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEwTURZd01USXdOREphRncweU56QTBNRFl3TVRJdwpOVEphTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkFJYUxvbFpaNzFKUkdtVVZsaWJOTkRSQjVLanM5K00KcWdxUExQWW8xQkNXRVg1MnNSNzdWM3JuaUlKSXd6bmwxWGQrelA3SnhnZ3pmODE0RnBha3JNbWpTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlJhCndYQURMR3hjb0F4T2pQZEE1K2dQVVN4UjhEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEzVGM2RGxicjdCRDIKR0V1aUkwbjVNMkIwYUVqeWY1NnVIUXhRMEJ6L1Q1UUNJRE44eUpIUHNmc0NHL3hzaTVObTA4TTh2Y0tYeGpGWApDNDlWWDZuYWNFeEUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1HVWNFaisvVElPUkdKaDB2eDdRTmMrT3duRWp1ay9XbXA0TmVLWGxENzlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQWhvdWlWbG52VWxFYVpSV1dKczAwTkVIa3FPejM0eXFDbzhzOWlqVUVKWVJmbmF4SHZ0WApldWVJZ2tqRE9lWFZkMzdNL3NuR0NETi96WGdXbHFTc3lRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
