apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clamav
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/williamdemarigny/Talos-CleanRoom.git
    targetRevision: main
    path: Resources/IAC-DNS/infrastructure/projects/clamav/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: clamav
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
