apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faraday
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:williamdemarigny/Talos-CleanRoom.git
    targetRevision: main
    path: apps/faraday
    directory:
      recurse: false
      exclude: '{application.yaml,*.sops.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: faraday
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
