#ENC[AES256_GCM,data:popJpAzELvpAGAXLb7COcehpdxJIw7Zgl+pVmRDwHV6nG326km05,iv:iFrIXWRPrirC9Sf8RCJyez/6Y2noN4YgkK784YDYyMU=,tag:IgQ3QhSAbA8CYWS5oEXtUw==,type:comment]
#ENC[AES256_GCM,data:/0tW1qqBOtOGHvDkkbQjpHMqbU8B5lJfPy1/513C5vxAnIUVJ70kEMTg/kvzeSissbyJ9qrSmkJLLk8+Tg==,iv:P5VB1tCOQpA9kLMF01oD5JXpF3l72F68svEQVj34gBo=,tag:DExltJROS1CLeGmHpSsh2g==,type:comment]
apiVersion: ENC[AES256_GCM,data:Y3M=,iv:XAACqkcRamwe9fPbVcalVc7kdwfaj01ry7a6zb4Fl7g=,tag:eNeWNxJ+9VImFgzekFBc1w==,type:str]
kind: ENC[AES256_GCM,data:Sfqf+kSg,iv:xGaEkXH9HKCM3vvFQ9lqRiGnGuiANsbiehaXtOO2CFQ=,tag:mOe5rEa14ZUKD2WvW4etwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZhrLdA6Hd39ZgVmvgnqVyPvYGw==,iv:QOcGKV0pW6EU4iWVJdrVFO1RXkSLtvxA5YDZ4pNDRhY=,tag:1yBoKKDEl8aItl90esJSlw==,type:str]
    namespace: ENC[AES256_GCM,data:YlBLBsENqw==,iv:7NHQX1IfSd2018vnX3/voUWIQ+0NFn5lFkPkhNOE4J0=,tag:2UJqpUfafejMBs3GRl36/g==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:5JJL0SCQ8Q==,iv:DSCGM2goDlIU4a9tLkMOtvPq+JrGUChC/G/fv9prT1I=,tag:q/yyg1FHrFRlnG0a7R1oGw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:TxW2Ic7gmm1oNPU=,iv:A1R30zzh55R8Vk9HGRfyXzuXRozvVoRtqHsaDz3n2Hg=,tag:2VkbWOUE5vynk5sVEwv77A==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:iQ7mcVyFqmbnYGbxKx8PWg==,iv:I8sH5yTjjkztHxZZsxAhJ6b6bmv8w49C4ROzfpRnTz4=,tag:qDENz0EphMx9TLX1WBU+vg==,type:str]
type: ENC[AES256_GCM,data:Vxk/SvUK,iv:8aSa8hZlOorj/FZWYt/j2UasuUuXDyYt8Y4QAEq7DCg=,tag:lBM+HCZMtyNCysoAFLL4Tg==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:CjVNGoKWMHbvGrU/mPHvgXKzfY0JvdyD,iv:bj8PLHhj3OBi1hb6Fg05HwemtBHCph5lN6akz2M8DDg=,tag:gj0m4ddy0uGU3Aoc+CMS4w==,type:str]
    admin-password: ENC[AES256_GCM,data:eUbiVNjE0rdbQwgM7RNTyA==,iv:pSmiNlHxeSOe0zHafw2SmSDz4x4XiMxcKtOtXxhmRUM=,tag:bwo4aiE1+OuebMSVcOhafQ==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS1IzNmtzRHkySjh4TXBn
            WkRpc0hYU2hmY0VqWFhXWjV2cFVDVzhaOVhjCkdEQ3dvN2pvSnphNXhEU2ErY0ZD
            aTJ3U0ptb2l0MWVLTDhDN241N21FTTAKLS0tIG5vQW0wTi9UdUVJdys4TVlad1By
            dkVEL2FLSUkyUDlKeEJPNlJXREdtZzQKNwbTCY4hOpXknxSzuLx7fej6vii1opTJ
            wlR7e8L/2p2rSMTmDcANWVDrWHbzEn+6OUHsR54p5MNmo95mxO5L8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T22:42:02Z"
    mac: ENC[AES256_GCM,data:DHxqSKTWJOy1wGHOBjmKTEuCZ+L7SM9RUdfYk829BHMSlvz0Awu0lmp2SQrPQ0yH313tM9V3dW4nu6dtKHRc4CNCfAD7FySwxuDt9xhr6NFoQ9gV8n9dfQhrgwnpcpeBF9DvVxjGmHGu9LSIWtIhkOY1wBiBb7xFkCaVzS8L7kU=,iv:O5R3eZBu3dRUJAALIBkPnpR4t8hxZPb1wd50KQpgrgQ=,tag:51/2zHJrCNbtNChhpgMS6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
