#ENC[AES256_GCM,data:Ye8KXJlR0IaoyIYgogLQmCoRz7JgvErT26/nTNb3K4k/aThuBnGW,iv:/tJ3QUxOerIoFqNmnOod0vzLjnfPmw6zZo0J+bDZNzk=,tag:1UnZDpQY2TuetMnxM4zCng==,type:comment]
#ENC[AES256_GCM,data:yfwNSJIop1ohjDQc6v0PrS2gBFAT0Pw0gfCngM6mu802xjom0rQzPh9aQs0eguXJUtVdTm856JYkaPYMPA==,iv:YJidE5CoWfbzIL4HoJw+SOB4cJEBGJf6PzS1qLqMDxs=,tag:7B8F2228T1O/oR+YNpNJDQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:K3M=,iv:SzDPeoanv3GjqsounRYoSFpmbY6SdcqfOJ07zwsAOds=,tag:eI+evudevW1Y0hr67i05UA==,type:str]
kind: ENC[AES256_GCM,data:XjIK8YD1,iv:mJY4HuxioMEIFU1R0F8P24WHQUBKk7qo0BKtrK/59MQ=,tag:4RoyzJIz2YWlbg+5evVZ3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rCKMve2Vdb51oK+40yQWd9ghKQ==,iv:SVhQVNm/p1alTTrCYIYXTS108PtQfJ5DzkIgA1/KssY=,tag:33xpqGvj7ijnd6BRwlLx7w==,type:str]
    namespace: ENC[AES256_GCM,data:3eL/+A3vug==,iv:NydnMKhs+7T8ShwoGO1TZxhQtulaEwCLMbxkbX6ohaU=,tag:i+SAsKGcJW9XuU1hMeH3Tw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:G+aMi41ssw==,iv:yXx27Lw1gIIkv3KROc1BF1clPONJDdeuZjAmFsUp+Zo=,tag:VTNuw/4EioP3n/tRqVdf0g==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:Lqg03vdiKUqF1vw=,iv:5B92zfdW+bDinDQqY276JTjQCt9Hy2ASIMfqn0jpiqE=,tag:f9v5bXR5AdbTtTwzTSsmSg==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:NklelQ3uIuyDzFzwWahHJA==,iv:2pJVdjc5Dnkz+D2/eaaj0EMzHwNHGAwBuZB5E/7wHw4=,tag:so37OFUYaCxVr2kSaG1xbQ==,type:str]
type: ENC[AES256_GCM,data:ExW1cEV4,iv:B9Og7i5bXXf1nks6lGUgNnzPQ8ag5Q+3Oj3yEID3u14=,tag:CJMGPbnUsVxucPVjfwnqGw==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:cJ9SkkUEVyX6eKIx9VMwfx66A2uWYFYe,iv:ZyXEf9Ke79agOpCXteD+OReyhVlD0yUTbfNH82Temg0=,tag:s067kd/6jCFoxBuzHj/fkQ==,type:str]
    admin-password: ENC[AES256_GCM,data:WVd5YCVLsJwTTgR6i/8Dsg==,iv:RzkRzH/WdbUJKyvoyxsUCebnIZwyvApKOl1DY1e21N4=,tag:WkZXpAavEZTY/DsegFFN/w==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUmZNOTNaUlhqUWhqL0dZ
            MlFGelBIVUZyK09mWFJ3U2lrbklCa2hSd1F3CmRnZEVMaVZjZC8veDZ4K3lHaHBi
            Y1NSSDc1Qmw0dWpGVjY3bnFyTDFGNXcKLS0tIHRacmxZV0toVTVtYldQSUg2YmNj
            b0RTQ2NLbmsxYVRXaExvS0RpREpQUU0KjEwF4Ig/MecIa3aR43/9jpGsl6nXj+Cr
            xOM7kQ6gfnN3KehbpVP8/OgqqmeUpBCA7J2G7jLNQqbF82brR6cqzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:18:03Z"
    mac: ENC[AES256_GCM,data:hOcRQxdjBZGtAggokUdjSlBpAZP3PhtcHOYDBf9epR87kziivoyjFqPr9/+mH1E75c5srwhJWG6GzNKpOtpGknc6JIS7MdjGfzdeOP5Gfl0FPDkN/iyCV+VdemwlVXugwtCiqJfeAplPh7S/s/BoEHFdWpQ4ofS2zkmXJ9NkwDA=,iv:BM1jRqDZlOKOXWwoNnMr9IhR4GBgYCwN3H3xPRLto4s=,tag:V7rnOVmagP8UXfQklKxsKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
