#ENC[AES256_GCM,data:D5ZL+0tipuBuA79bTXwf3465xLpSWUKvRpiNvQdOL3ETI4iOqmjt,iv:eS7c1mWk9hgsKTFT9uT/9EgTLnR8qm/ioeupNWF5jvI=,tag:pNPfXfpKS4Ejxcy9BdTo1A==,type:comment]
#ENC[AES256_GCM,data:rbeIh85UbZ7NX40NNQLAZvQoBWG6OYMBip5ahQ4OfZ3Ynow4qiBsstIsDVq0r4/40yGkzS2SisrTxaZHpQ==,iv:mGftumgb9gwgZH4umzzmxsJQGkZ0z6f1T9nz43+CHqM=,tag:nbtzNwxWE2abvwnntkpwXw==,type:comment]
apiVersion: ENC[AES256_GCM,data:/xE=,iv:T53tBqHB0sT5l1B4XDHk228HyGfJty2ODYTdFvVzx2Q=,tag:tgecndi0Wsr+Sf3NjvqiRw==,type:str]
kind: ENC[AES256_GCM,data:7vwmzkja,iv:wAXgDmSNrldEI0ufv4vWpdIfIe70Du1onXZ7xtZi8so=,tag:mZigKOPLwt/hNle13eIFEw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mKAM8HqMXlmufDMZDgp5521Ddw==,iv:NFgvMLEzCdFbA8vIttCEMIKJG1+GBZuTjlcJzZSiBZE=,tag:t8s1etgRpZILI1W1+Cb2lg==,type:str]
    namespace: ENC[AES256_GCM,data:iqvaa+6y/A==,iv:k3y7j4VqCPtyaPD5ClhbCanWP10in8q6LQn4XBsGxH8=,tag:gXTlvd9LoflfRb65Eugh0w==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:A2v+ckk6ew==,iv:x7b9fO0fkfmSbljbbssFFETY4/wKumEFZY7AVDug9fY=,tag:iz/VZ6jtVS7uzruTUkK3aw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:5s0s5EgHtJIdyF0=,iv:uexwT45KxtPVCNByRw3sX1hBrrXbGEcwfcocxZptR/o=,tag:GniUJkYa+r/mbMfwhp8umw==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:Y6y6mUpCM6sQHMUm7l+gIA==,iv:NfzltRe0Thm6AegbWoZpYur7mk1KLKE6rFlUXZ4w5ys=,tag:pVsFaXCMadVm2TI2f93V/A==,type:str]
type: ENC[AES256_GCM,data:DMNK/dVm,iv:2jYEVKiPspRyqSsRr+7qw/yvQpenj5YpasRwnqN/qjQ=,tag:Y/Ziuv2LjXMaCyftW0f6sQ==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:NrN4G38v33LxYh3MtPnnMuQ9tNOgUn/I,iv:OzskZPT1Yd0NOX+YPrzAE8NEKBwZ7Ei7f4yZTjFK78U=,tag:TzKQvdE3x2U13dlzeFXuKw==,type:str]
    admin-password: ENC[AES256_GCM,data:o4jFFXih5YZR0F4Q0fqSob/Ixg4Vqlqq,iv:aNetI/8p7RJe6Ua8iVY3qKDwMuB0h8VbgAkbEDbvZEE=,tag:oSP/4t1gSIpNdL0E8ClnTg==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR1RmQkZvanVla2xOd1Zp
            R3JCUy92cXFPSy8wNTZoTXdUVDV6Yi9kWFQ4Ckd2cmNLbThRdjZnUVBxeE9ReHUw
            dVZkeStVTFJTdDFzemxncHVQVEMrRk0KLS0tIDU0elpWb05KYWdnWEVMVWxMTHlG
            MEgrSjNqb3JyZTk5WXdXbVRjU3JhM3cKag70zz6Y0BHA/GQmbjmIMO4KvOeJ6Uge
            CAU0itazS1pwH9bCk/iDy4NXO5FZliTNfUfX03ht7ubOgWyzyWjkCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:52:36Z"
    mac: ENC[AES256_GCM,data:gpn0erglYoNS19/J8hh90IZta/7I8Zr2CwJ4pgC5zW0uNm+1/s5gMzMw2ltLktK61rj5G7kjsSbsFUvDriFW0If/xjFc5fH+CbIAYP9735NXj3+0RPjEPP7KrwnRgR0F65t8sldEorn4un6Y+1nrEQO37p2VMkBOzcWrdJ3s6Ns=,iv:GjsONUMmr+rFYlBkSdDS+7C4mjE4EBut8QNH1KA86IY=,tag:J+EryPMevuLuU1KU7EeLgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
