# =============================================================================
# OPNSense API Testing and Backup Configuration
# =============================================================================
# This file provides simple API connectivity tests and backup functionality
# to verify OPNSense API communication before attempting complex configurations.

locals {
  # Determine if API testing should be enabled
  opnsense_api_enabled = var.opnsense_enabled && var.opnsense_api_key != "" && var.opnsense_api_secret != ""

  # Get the primary OPNSense instance (first one in the list)
  primary_opnsense = local.opnsense_api_enabled && length(var.opnsense_vms) > 0 ? var.opnsense_vms[0] : null

  # Primary API connection target - use IP address if available (for initial connection before hostname is configured)
  # Falls back to FQDN if no IP address is specified
  primary_api_host = local.primary_opnsense != null ? (
    local.primary_opnsense.ip_address != null ? local.primary_opnsense.ip_address : local.primary_opnsense.fqdn
  ) : ""

  # Primary API URL for testing (uses IP address to avoid DNS rebind issues)
  primary_api_url = local.primary_opnsense != null ? "${var.opnsense_api_protocol}://${local.primary_api_host}:${var.opnsense_api_port}/api" : ""

  # Backup output directory
  backup_output_dir = "${path.module}/opnsense_backups"

  # Timestamp for backup filename
  backup_timestamp = formatdate("YYYY-MM-DD_hh-mm-ss", timestamp())
}

# =============================================================================
# PowerShell Script for API Testing and Backup
# =============================================================================

# Generate the PowerShell script for OPNSense API operations
resource "local_file" "opnsense_api_script" {
  count    = local.opnsense_api_enabled ? 1 : 0
  filename = "${path.module}/scripts/opnsense_api_operations.ps1"
  content  = <<-POWERSHELL
# OPNSense API Operations Script
# Generated by Terraform - Do not edit manually
# This script provides API connectivity testing and backup functionality

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("test", "backup", "info")]
    [string]$Operation,

    [Parameter(Mandatory=$false)]
    [string]$OutputPath = "."
)

# Configuration - credentials are base64 encoded to avoid escaping issues
$ApiUrl = "${local.primary_api_url}"
$ApiKeyB64 = "${base64encode(var.opnsense_api_key)}"
$ApiSecretB64 = "${base64encode(var.opnsense_api_secret)}"
$SkipCert = [System.Convert]::ToBoolean("${var.opnsense_api_insecure}")
$FwName = "${local.primary_opnsense != null ? local.primary_opnsense.name : "unknown"}"

# Decode credentials from base64
$ApiKey = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($ApiKeyB64))
$ApiSecret = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($ApiSecretB64))

# Create credential for Basic Authentication
$AuthString = "$${ApiKey}:$${ApiSecret}"
$AuthBytes = [System.Text.Encoding]::UTF8.GetBytes($AuthString)
$AuthBase64 = [System.Convert]::ToBase64String($AuthBytes)

# Configure SSL certificate handling for PowerShell 5.1 compatibility
if ($SkipCert) {
    if ($PSVersionTable.PSVersion.Major -lt 6) {
        # PowerShell 5.1 - Use .NET callback
        Add-Type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCertsPolicy : ICertificatePolicy {
    public bool CheckValidationResult(
        ServicePoint srvPoint, X509Certificate certificate,
        WebRequest request, int certificateProblem) {
        return true;
    }
}
"@
        [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
    }
}

function Invoke-OPNSenseAPI {
    param(
        [string]$Endpoint,
        [string]$Method = "GET",
        [hashtable]$Body = $null
    )

    $Uri = "$${ApiUrl}$${Endpoint}"
    $Headers = @{
        "Authorization" = "Basic $${AuthBase64}"
    }

    try {
        # Disable default proxy to prevent proxy configuration errors
        [System.Net.WebRequest]::DefaultWebProxy = $null

        $params = @{
            Uri = $Uri
            Method = $Method
            Headers = $Headers
            UseBasicParsing = $true
        }

        if ($Body) {
            $Headers["Content-Type"] = "application/json"
            $params["Body"] = ($Body | ConvertTo-Json -Depth 10)
        }

        # PowerShell version-specific certificate handling
        if ($SkipCert -and $PSVersionTable.PSVersion.Major -ge 6) {
            $params["SkipCertificateCheck"] = $true
        }

        $response = Invoke-WebRequest @params
        return @{
            Success = $true
            StatusCode = $response.StatusCode
            Content = $response.Content
        }
    }
    catch {
        return @{
            Success = $false
            Error = $_.Exception.Message
            StatusCode = if ($_.Exception.Response) { $_.Exception.Response.StatusCode.value__ } else { 0 }
        }
    }
}

function Test-APIConnectivity {
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "OPNSense API Connectivity Tests" -ForegroundColor Cyan
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Target: $${FwName}" -ForegroundColor Yellow
    Write-Host "API URL: $${ApiUrl}" -ForegroundColor Yellow
    Write-Host "Skip Certificate Check: $${SkipCert}" -ForegroundColor Yellow
    Write-Host ""

    $tests = @(
        @{ Name = "Core System Status"; Endpoint = "/core/system/status"; Method = "GET" },
        @{ Name = "Firmware Status"; Endpoint = "/core/firmware/status"; Method = "POST" },
        @{ Name = "Interface List"; Endpoint = "/diagnostics/interface/getInterfaceNames"; Method = "GET" },
        @{ Name = "General Settings"; Endpoint = "/core/firmware/getOptions"; Method = "GET" }
    )

    $passed = 0
    $failed = 0

    foreach ($test in $tests) {
        Write-Host "Testing: $($test.Name)..." -NoNewline
        $result = Invoke-OPNSenseAPI -Endpoint $test.Endpoint -Method $test.Method

        if ($result.Success) {
            Write-Host " PASSED" -ForegroundColor Green
            Write-Host "  Status Code: $($result.StatusCode)" -ForegroundColor Gray
            $passed++
        } else {
            Write-Host " FAILED" -ForegroundColor Red
            Write-Host "  Error: $($result.Error)" -ForegroundColor Gray
            Write-Host "  Status Code: $($result.StatusCode)" -ForegroundColor Gray
            $failed++
        }
    }

    Write-Host ""
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "Test Results: $${passed} passed, $${failed} failed" -ForegroundColor $(if ($failed -eq 0) { "Green" } else { "Yellow" })
    Write-Host "=============================================" -ForegroundColor Cyan

    return ($failed -eq 0)
}

function Get-SystemInfo {
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "OPNSense System Information" -ForegroundColor Cyan
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host ""

    # Get system status
    $status = Invoke-OPNSenseAPI -Endpoint "/core/system/status" -Method "GET"
    if ($status.Success) {
        Write-Host "System Status:" -ForegroundColor Yellow
        $statusData = $status.Content | ConvertFrom-Json
        $statusData | Format-List
    }

    # Get firmware info
    $firmware = Invoke-OPNSenseAPI -Endpoint "/core/firmware/status" -Method "POST"
    if ($firmware.Success) {
        Write-Host "Firmware Information:" -ForegroundColor Yellow
        $firmwareData = $firmware.Content | ConvertFrom-Json
        Write-Host "  Product: $($firmwareData.product_name)" -ForegroundColor Gray
        Write-Host "  Version: $($firmwareData.product_version)" -ForegroundColor Gray
    }

    # Get interfaces
    $interfaces = Invoke-OPNSenseAPI -Endpoint "/diagnostics/interface/getInterfaceNames" -Method "GET"
    if ($interfaces.Success) {
        Write-Host "Interfaces:" -ForegroundColor Yellow
        $interfaceData = $interfaces.Content | ConvertFrom-Json
        $interfaceData.PSObject.Properties | ForEach-Object {
            Write-Host "  $($_.Name): $($_.Value)" -ForegroundColor Gray
        }
    }

    # Check installed plugins
    $plugins = Invoke-OPNSenseAPI -Endpoint "/core/firmware/info" -Method "GET"
    if ($plugins.Success) {
        Write-Host "Installed Plugins:" -ForegroundColor Yellow
        try {
            $pluginData = $plugins.Content | ConvertFrom-Json
            if ($pluginData.package) {
                $pluginData.package | Where-Object { $_.installed -eq "1" } | ForEach-Object {
                    Write-Host "  $($_.name) - $($_.version)" -ForegroundColor Gray
                }
            }
        } catch {
            Write-Host "  Unable to parse plugin data" -ForegroundColor Gray
        }
    }
}

function Create-Backup {
    param([string]$OutputPath)

    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "Creating OPNSense Configuration Backup" -ForegroundColor Cyan
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host ""

    # Ensure output directory exists
    if (-not (Test-Path $OutputPath)) {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
        Write-Host "Created output directory: $${OutputPath}" -ForegroundColor Gray
    }

    $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
    $backupFilename = "$${FwName}_backup_$${timestamp}.xml"
    $backupPath = Join-Path $OutputPath $backupFilename

    Write-Host "Downloading backup from $${FwName}..." -ForegroundColor Yellow

    # OPNSense backup API endpoint
    $backupEndpoint = "/core/backup/download/this"

    $Uri = "$${ApiUrl}$${backupEndpoint}"
    $Headers = @{
        "Authorization" = "Basic $${AuthBase64}"
    }

    try {
        # Disable default proxy to prevent proxy configuration errors
        [System.Net.WebRequest]::DefaultWebProxy = $null

        $params = @{
            Uri = $Uri
            Method = "GET"
            Headers = $Headers
            OutFile = $backupPath
            UseBasicParsing = $true
        }

        if ($SkipCert -and $PSVersionTable.PSVersion.Major -ge 6) {
            $params["SkipCertificateCheck"] = $true
        }

        Invoke-WebRequest @params

        if (Test-Path $backupPath) {
            $fileInfo = Get-Item $backupPath
            Write-Host ""
            Write-Host "Backup created successfully!" -ForegroundColor Green
            Write-Host "  File: $${backupPath}" -ForegroundColor Gray
            Write-Host "  Size: $([math]::Round($fileInfo.Length / 1KB, 2)) KB" -ForegroundColor Gray
            return $true
        } else {
            Write-Host "Backup file was not created" -ForegroundColor Red
            return $false
        }
    }
    catch {
        Write-Host "Backup failed: $($_.Exception.Message)" -ForegroundColor Red

        # Try alternative backup method
        Write-Host ""
        Write-Host "Trying alternative backup method..." -ForegroundColor Yellow

        try {
            $altEndpoint = "/core/backup/backup/this"
            $altResult = Invoke-OPNSenseAPI -Endpoint $altEndpoint -Method "POST" -Body @{}

            if ($altResult.Success) {
                $altResult.Content | Out-File -FilePath $backupPath -Encoding UTF8
                Write-Host "Alternative backup succeeded!" -ForegroundColor Green
                Write-Host "  File: $${backupPath}" -ForegroundColor Gray
                return $true
            }
        }
        catch {
            Write-Host "Alternative method also failed: $($_.Exception.Message)" -ForegroundColor Red
        }

        return $false
    }
}

# Main execution
switch ($Operation) {
    "test" {
        $result = Test-APIConnectivity
        exit $(if ($result) { 0 } else { 1 })
    }
    "backup" {
        $result = Create-Backup -OutputPath $OutputPath
        exit $(if ($result) { 0 } else { 1 })
    }
    "info" {
        Get-SystemInfo
        exit 0
    }
}
POWERSHELL

  file_permission = "0755"

  depends_on = [proxmox_virtual_environment_vm.opnsense]
}

# Create the scripts directory
resource "local_file" "scripts_dir_placeholder" {
  count    = local.opnsense_api_enabled ? 1 : 0
  filename = "${path.module}/scripts/.gitkeep"
  content  = "# Placeholder to ensure scripts directory exists\n"

  depends_on = [proxmox_virtual_environment_vm.opnsense]
}

# Create the backup output directory
resource "local_file" "backup_dir_placeholder" {
  count    = local.opnsense_api_enabled ? 1 : 0
  filename = "${path.module}/opnsense_backups/.gitkeep"
  content  = "# OPNSense backup files directory\n# Backups are stored here with timestamp naming\n"

  depends_on = [proxmox_virtual_environment_vm.opnsense]
}

# =============================================================================
# API Connectivity Test Task
# =============================================================================

# Wait for OPNSense VMs to be fully booted and API available
resource "time_sleep" "wait_for_opnsense_boot" {
  count           = local.opnsense_api_enabled ? 1 : 0
  create_duration = "120s" # Wait 2 minutes for VMs to boot

  depends_on = [
    proxmox_virtual_environment_vm.opnsense,
    local_file.opnsense_api_script
  ]
}

# Run API connectivity test
resource "null_resource" "opnsense_api_test" {
  count = local.opnsense_api_enabled ? 1 : 0

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    interpreter = ["powershell", "-Command"]
    command     = <<-EOT
      Write-Host ""
      Write-Host "======================================================" -ForegroundColor Magenta
      Write-Host "  OPNSense API Connectivity Test" -ForegroundColor Magenta
      Write-Host "======================================================" -ForegroundColor Magenta
      Write-Host ""

      $scriptPath = "${replace(path.module, "/", "\\")}\\scripts\\opnsense_api_operations.ps1"

      if (Test-Path $scriptPath) {
          & $scriptPath -Operation "test"
      } else {
          Write-Host "ERROR: Script not found at $scriptPath" -ForegroundColor Red
          exit 1
      }
    EOT
  }

  depends_on = [
    time_sleep.wait_for_opnsense_boot,
    local_file.opnsense_api_script
  ]
}

# =============================================================================
# Backup Download Task
# =============================================================================

# Create backup and download to host
resource "null_resource" "opnsense_backup" {
  count = local.opnsense_api_enabled ? 1 : 0

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    interpreter = ["powershell", "-Command"]
    command     = <<-EOT
      Write-Host ""
      Write-Host "======================================================" -ForegroundColor Magenta
      Write-Host "  OPNSense Configuration Backup" -ForegroundColor Magenta
      Write-Host "======================================================" -ForegroundColor Magenta
      Write-Host ""

      $scriptPath = "${replace(path.module, "/", "\\")}\\scripts\\opnsense_api_operations.ps1"
      $backupPath = "${replace(path.module, "/", "\\")}\\opnsense_backups"

      if (Test-Path $scriptPath) {
          & $scriptPath -Operation "backup" -OutputPath $backupPath
      } else {
          Write-Host "ERROR: Script not found at $scriptPath" -ForegroundColor Red
          exit 1
      }
    EOT
  }

  depends_on = [
    null_resource.opnsense_api_test
  ]
}

# =============================================================================
# System Info Task (Optional - for debugging)
# =============================================================================

resource "null_resource" "opnsense_system_info" {
  count = local.opnsense_api_enabled ? 1 : 0

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    interpreter = ["powershell", "-Command"]
    command     = <<-EOT
      Write-Host ""
      Write-Host "======================================================" -ForegroundColor Magenta
      Write-Host "  OPNSense System Information" -ForegroundColor Magenta
      Write-Host "======================================================" -ForegroundColor Magenta
      Write-Host ""

      $scriptPath = "${replace(path.module, "/", "\\")}\\scripts\\opnsense_api_operations.ps1"

      if (Test-Path $scriptPath) {
          & $scriptPath -Operation "info"
      } else {
          Write-Host "ERROR: Script not found at $scriptPath" -ForegroundColor Red
          exit 1
      }
    EOT
  }

  depends_on = [
    null_resource.opnsense_backup
  ]
}

# =============================================================================
# Outputs
# =============================================================================

output "opnsense_api_test_status" {
  description = "OPNSense API test configuration status"
  sensitive   = true
  value = local.opnsense_api_enabled ? {
    enabled          = true
    target_firewall  = local.primary_opnsense != null ? local.primary_opnsense.name : null
    target_fqdn      = local.primary_opnsense != null ? local.primary_opnsense.fqdn : null
    api_url          = local.primary_api_url
    backup_directory = local.backup_output_dir
    script_path      = "${path.module}/scripts/opnsense_api_operations.ps1"
  } : {
    enabled          = false
    target_firewall  = null
    target_fqdn      = null
    api_url          = null
    backup_directory = null
    script_path      = null
  }
}
