# OPNSense API Operations Script
# Generated by Terraform - Do not edit manually
# This script provides API connectivity testing and backup functionality

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("test", "backup", "info")]
    [string]$Operation,

    [Parameter(Mandatory=$false)]
    [string]$OutputPath = "."
)

# Configuration - credentials are base64 encoded to avoid escaping issues
$ApiUrl = "https://10.83.3.5:443/api"
$ApiKeyB64 = "T3g3cHB4dG1hRFNqMlNKOFBhUGtjL2M0QWw4enhMMnM3elhRT3ZObjRDSnZpNXM5YWZWSS90eHZTWVZGamk1U1VXTEE3TkJmVzN2U0dsbDM="
$ApiSecretB64 = "bmpPYjNwdVc1VHBhc05kZUtHOTlOek9FSUZ6Z1VzTEgrSkFqMnBCRFplTlBJZ1IxRHgwTVYzbGcxRCtLOFV3eDRFYzFPSmYySzgrU1UyRnM="
$SkipCert = [System.Convert]::ToBoolean("true")
$FwName = "opnsense-fw-01"

# Decode credentials from base64
$ApiKey = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($ApiKeyB64))
$ApiSecret = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($ApiSecretB64))

# Create credential for Basic Authentication
$AuthString = "${ApiKey}:${ApiSecret}"
$AuthBytes = [System.Text.Encoding]::UTF8.GetBytes($AuthString)
$AuthBase64 = [System.Convert]::ToBase64String($AuthBytes)

# Configure SSL certificate handling for PowerShell 5.1 compatibility
if ($SkipCert) {
    if ($PSVersionTable.PSVersion.Major -lt 6) {
        # PowerShell 5.1 - Use .NET callback
        Add-Type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCertsPolicy : ICertificatePolicy {
    public bool CheckValidationResult(
        ServicePoint srvPoint, X509Certificate certificate,
        WebRequest request, int certificateProblem) {
        return true;
    }
}
"@
        [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
    }
}

function Invoke-OPNSenseAPI {
    param(
        [string]$Endpoint,
        [string]$Method = "GET",
        [hashtable]$Body = $null
    )

    $Uri = "${ApiUrl}${Endpoint}"
    $Headers = @{
        "Authorization" = "Basic ${AuthBase64}"
    }

    try {
        # Disable default proxy to prevent proxy configuration errors
        [System.Net.WebRequest]::DefaultWebProxy = $null

        $params = @{
            Uri = $Uri
            Method = $Method
            Headers = $Headers
            UseBasicParsing = $true
        }

        if ($Body) {
            $Headers["Content-Type"] = "application/json"
            $params["Body"] = ($Body | ConvertTo-Json -Depth 10)
        }

        # PowerShell version-specific certificate handling
        if ($SkipCert -and $PSVersionTable.PSVersion.Major -ge 6) {
            $params["SkipCertificateCheck"] = $true
        }

        $response = Invoke-WebRequest @params
        return @{
            Success = $true
            StatusCode = $response.StatusCode
            Content = $response.Content
        }
    }
    catch {
        return @{
            Success = $false
            Error = $_.Exception.Message
            StatusCode = if ($_.Exception.Response) { $_.Exception.Response.StatusCode.value__ } else { 0 }
        }
    }
}

function Test-APIConnectivity {
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "OPNSense API Connectivity Tests" -ForegroundColor Cyan
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Target: ${FwName}" -ForegroundColor Yellow
    Write-Host "API URL: ${ApiUrl}" -ForegroundColor Yellow
    Write-Host "Skip Certificate Check: ${SkipCert}" -ForegroundColor Yellow
    Write-Host ""

    $tests = @(
        @{ Name = "Core System Status"; Endpoint = "/core/system/status"; Method = "GET" },
        @{ Name = "Firmware Status"; Endpoint = "/core/firmware/status"; Method = "POST" },
        @{ Name = "Interface List"; Endpoint = "/diagnostics/interface/getInterfaceNames"; Method = "GET" },
        @{ Name = "General Settings"; Endpoint = "/core/firmware/getOptions"; Method = "GET" }
    )

    $passed = 0
    $failed = 0

    foreach ($test in $tests) {
        Write-Host "Testing: $($test.Name)..." -NoNewline
        $result = Invoke-OPNSenseAPI -Endpoint $test.Endpoint -Method $test.Method

        if ($result.Success) {
            Write-Host " PASSED" -ForegroundColor Green
            Write-Host "  Status Code: $($result.StatusCode)" -ForegroundColor Gray
            $passed++
        } else {
            Write-Host " FAILED" -ForegroundColor Red
            Write-Host "  Error: $($result.Error)" -ForegroundColor Gray
            Write-Host "  Status Code: $($result.StatusCode)" -ForegroundColor Gray
            $failed++
        }
    }

    Write-Host ""
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "Test Results: ${passed} passed, ${failed} failed" -ForegroundColor $(if ($failed -eq 0) { "Green" } else { "Yellow" })
    Write-Host "=============================================" -ForegroundColor Cyan

    return ($failed -eq 0)
}

function Get-SystemInfo {
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "OPNSense System Information" -ForegroundColor Cyan
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host ""

    # Get system status
    $status = Invoke-OPNSenseAPI -Endpoint "/core/system/status" -Method "GET"
    if ($status.Success) {
        Write-Host "System Status:" -ForegroundColor Yellow
        $statusData = $status.Content | ConvertFrom-Json
        $statusData | Format-List
    }

    # Get firmware info
    $firmware = Invoke-OPNSenseAPI -Endpoint "/core/firmware/status" -Method "POST"
    if ($firmware.Success) {
        Write-Host "Firmware Information:" -ForegroundColor Yellow
        $firmwareData = $firmware.Content | ConvertFrom-Json
        Write-Host "  Product: $($firmwareData.product_name)" -ForegroundColor Gray
        Write-Host "  Version: $($firmwareData.product_version)" -ForegroundColor Gray
    }

    # Get interfaces
    $interfaces = Invoke-OPNSenseAPI -Endpoint "/diagnostics/interface/getInterfaceNames" -Method "GET"
    if ($interfaces.Success) {
        Write-Host "Interfaces:" -ForegroundColor Yellow
        $interfaceData = $interfaces.Content | ConvertFrom-Json
        $interfaceData.PSObject.Properties | ForEach-Object {
            Write-Host "  $($_.Name): $($_.Value)" -ForegroundColor Gray
        }
    }

    # Check installed plugins
    $plugins = Invoke-OPNSenseAPI -Endpoint "/core/firmware/info" -Method "GET"
    if ($plugins.Success) {
        Write-Host "Installed Plugins:" -ForegroundColor Yellow
        try {
            $pluginData = $plugins.Content | ConvertFrom-Json
            if ($pluginData.package) {
                $pluginData.package | Where-Object { $_.installed -eq "1" } | ForEach-Object {
                    Write-Host "  $($_.name) - $($_.version)" -ForegroundColor Gray
                }
            }
        } catch {
            Write-Host "  Unable to parse plugin data" -ForegroundColor Gray
        }
    }
}

function Create-Backup {
    param([string]$OutputPath)

    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "Creating OPNSense Configuration Backup" -ForegroundColor Cyan
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host ""

    # Ensure output directory exists
    if (-not (Test-Path $OutputPath)) {
        New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
        Write-Host "Created output directory: ${OutputPath}" -ForegroundColor Gray
    }

    $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
    $backupFilename = "${FwName}_backup_${timestamp}.xml"
    $backupPath = Join-Path $OutputPath $backupFilename

    Write-Host "Downloading backup from ${FwName}..." -ForegroundColor Yellow

    # OPNSense backup API endpoint
    $backupEndpoint = "/core/backup/download/this"

    $Uri = "${ApiUrl}${backupEndpoint}"
    $Headers = @{
        "Authorization" = "Basic ${AuthBase64}"
    }

    try {
        # Disable default proxy to prevent proxy configuration errors
        [System.Net.WebRequest]::DefaultWebProxy = $null

        $params = @{
            Uri = $Uri
            Method = "GET"
            Headers = $Headers
            OutFile = $backupPath
            UseBasicParsing = $true
        }

        if ($SkipCert -and $PSVersionTable.PSVersion.Major -ge 6) {
            $params["SkipCertificateCheck"] = $true
        }

        Invoke-WebRequest @params

        if (Test-Path $backupPath) {
            $fileInfo = Get-Item $backupPath
            Write-Host ""
            Write-Host "Backup created successfully!" -ForegroundColor Green
            Write-Host "  File: ${backupPath}" -ForegroundColor Gray
            Write-Host "  Size: $([math]::Round($fileInfo.Length / 1KB, 2)) KB" -ForegroundColor Gray
            return $true
        } else {
            Write-Host "Backup file was not created" -ForegroundColor Red
            return $false
        }
    }
    catch {
        Write-Host "Backup failed: $($_.Exception.Message)" -ForegroundColor Red

        # Try alternative backup method
        Write-Host ""
        Write-Host "Trying alternative backup method..." -ForegroundColor Yellow

        try {
            $altEndpoint = "/core/backup/backup/this"
            $altResult = Invoke-OPNSenseAPI -Endpoint $altEndpoint -Method "POST" -Body @{}

            if ($altResult.Success) {
                $altResult.Content | Out-File -FilePath $backupPath -Encoding UTF8
                Write-Host "Alternative backup succeeded!" -ForegroundColor Green
                Write-Host "  File: ${backupPath}" -ForegroundColor Gray
                return $true
            }
        }
        catch {
            Write-Host "Alternative method also failed: $($_.Exception.Message)" -ForegroundColor Red
        }

        return $false
    }
}

# Main execution
switch ($Operation) {
    "test" {
        $result = Test-APIConnectivity
        exit $(if ($result) { 0 } else { 1 })
    }
    "backup" {
        $result = Create-Backup -OutputPath $OutputPath
        exit $(if ($result) { 0 } else { 1 })
    }
    "info" {
        Get-SystemInfo
        exit 0
    }
}
