apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openvas
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
  annotations:
    # Deploy after Ceph CSI (needs storage class)
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:williamdemarigny/Talos-CleanRoom.git
    targetRevision: refactor/restructure
    path: apps/openvas
    directory:
      recurse: false
      exclude: 'application.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: openvas
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
