#ENC[AES256_GCM,data:REsuy7W4lBkOe0E9ePBdT1ZWo/9jDxf9WyZh4/r5,iv:fkxsQgJmdzX8qLsBDxZKIAhnKFDVOt99c2dVHK0503s=,tag:LCng4XCYZm9QXhcXu+j2xQ==,type:comment]
#ENC[AES256_GCM,data:ZUq8zUKc8tV8Djg2ntMj+De5tJS17LWHIXemc+dFb2Gtl0UJidyJE6hmhKRORGnnaZi8r9OmCp5euoyqvw==,iv:KRhlvuSpeV2CaxGteYj+S6R4LvTg4NRQb9blPkFBenc=,tag:j1qhiTaG5AvTl8N3/qTDaw==,type:comment]
apiVersion: ENC[AES256_GCM,data:AWo=,iv:wijakWooV+c39lYfwX04SXzouQ8GQyEFXqrxEIpmGUQ=,tag:7NnUQ7K97WGO9xS5wYg/uQ==,type:str]
kind: ENC[AES256_GCM,data:jYDtYmti,iv:IHxyOOmRPzTslqvO6ZsCo9Yu2cWT+F5Okrek8Xi0VvQ=,tag:EaSfd9vispCOOcJLQmm+pw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nWtotlFUKXbAjk3ZAsYiOWdDQQ==,iv:7Cfp8lS9q2uK1kzWxIQGwBIcl28PLp2OaNt/YtCE3M4=,tag:z0i3dw1PgBIas33+rRDk4Q==,type:str]
    namespace: ENC[AES256_GCM,data:H5mr4Jv/Sg==,iv:TusXzgpnA751ta9fb5hcKuPMtkRsmjOKix9TJmH2GDY=,tag:6TvjCPxEfcA07na5GMY/Ow==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:IgzaFEHe9Q==,iv:3/UO/6woGewvx7KsFXE7qhbju3GnCdRS5z+sm7B3q0Y=,tag:v3HB0AQJTRlOeFZpy99Hmw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:p9Y/jmwJCIWlzvI=,iv:KEs05dqpk8GS7ip8YJAEsQSwhwJEWYPZkAfGq+obBNU=,tag:QOOHCsZzdFxh4EB+ckyaGA==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:cYRHllCpr17JYntxyT+enw==,iv:PdY5pDgZV0QK2hJvjNpM1v5Hfok2e+k16aWApMmISTo=,tag:mqgdMablkTKPsokGzJLysg==,type:str]
type: ENC[AES256_GCM,data:nBkRyx8H,iv:Vuupy3mkyKKhfZDvwJHH2DXRFRabNOaYfGujYIvelpM=,tag:qkcVuyCMsv4OT8K7pMCmUA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:V+qZyd8S+lWLhEBMC9xZqw==,iv:9OsdUK/+GJ/eBMQgdFkx/BJaYNh2btNKZnzr1GREqdQ=,tag:E50lpRpi2yTBl9kvbomADw==,type:str]
    postgres-password: ENC[AES256_GCM,data:NriZITnPqD9FXFmTQ3MWii7x0e2DhhZZ,iv:pb4XoeSqtD50IFhQaSM8qlSM4mlaUp0QrGE19B3q4uc=,tag:Qu5i+GX2q5KVWceiAu+xSA==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQXdZYjJ4WWZOcXBlWTRi
            d3pYaUhSWUZ6MEQ3UXRWTGJieEdhTnkzTjI4CnppUml5UkF3ZjN2NGlsUytDM3hp
            ZnZudVdYUnh5eFJqeGUwb0M5R05iZWsKLS0tIEZuZGdwWCt2RkU4NnRLaGFYRFJN
            RXU2a2FUUGlQR0tmV2hNSC9Od0syUjgKmOoqJ/sCMMS1ZBnXcvPe9EUtBHP5re5h
            IlSd18rnE4EfZYF4OZWhyBk6l5+hubm7ERjdl56HFSP1Y0E9EBglQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T22:42:02Z"
    mac: ENC[AES256_GCM,data:C6qn2V2K5yl05WGT8RiihPTZhUpHVbpk/62rEnX0LCQVypi7ARA3mFDublYOlYe8uOUUfSIxAc+zFAWIRwX6i51R6qtdXsV8ZxcufGDRg7fAcHX/8Kqx4KBKgXHvoTzdXILLDqylnYrYggEBNGJgg66WwGt+omYByZDmpLJxQ4c=,iv:XqlkfUdcrBwpBf623KF9VGZdktHb7Tk+fY+FtPZHqKs=,tag:f995EUJGnQSVnA3Bhf0kGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
