#ENC[AES256_GCM,data:fdRnll3+Eq1Fc2nq2II7nnZT2tRDJXz13XUS7gLV,iv:UMl85Y0NpNxLYhnQ9JG32Ydx/DZwmXp5jZTd1DZ8a1o=,tag:t5Chjs2lYo2HDMMB382fjQ==,type:comment]
#ENC[AES256_GCM,data:xP6tfh+mMNoFwmA7DYS8CqCCLm8Q2JYVhWP/cxQ9BayXjqirGhnaF0WMeRWNUAj389+1Q1NzuQtZY15crA==,iv:2oQrUQ4vQYhEhh5D6ycc2ZQM/IiGsOi489Ilrnwpnjk=,tag:al234SjHNNSdJbDilfzrDA==,type:comment]
apiVersion: ENC[AES256_GCM,data:0X4=,iv:UN8mzqc1qjTelxUxlF8Oob669TfZl6axrLfJ1suZc7I=,tag:Vg42ll8WsPZ6hedMqR6mQw==,type:str]
kind: ENC[AES256_GCM,data:MuvgI3r1,iv:9oDlNbFJiL+aNGO3SAg66sR9uYg6GLJe1RgaKl7+q60=,tag:bLnMsnVGD828zdYWZK4noQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BPRFFW7DQGVNwFniNwJ0e9yOaA==,iv:dgcsngXZn5501ToFOQ3KrTtov1yzYIS/BtYXNeWUB4g=,tag:bwzS16sN2aQH5lMJjR1IBA==,type:str]
    namespace: ENC[AES256_GCM,data:ZTuDeKMRLQ==,iv:IAmyH+iyUeerzzA/l/vKDDm9o0hGBkhqRdyrjVB0DM8=,tag:XakQ5sSFvCslTCHU/Lm/Eg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:jpGvhQfCdw==,iv:kFb+MHEFjNcekkk0Lv+WW+pGsEgzJTr2SbDO0xHe+j8=,tag:OvA7ZpREXEtYEEhynqEphg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:6x3XGdDT/SfG6dc=,iv:yTpnbhWOZN3/M8wRUkFXOdZa5Y6S6q5bpL9lIVzXDAw=,tag:jD2Q+x9TOITwR8YCOCZymg==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:+hntb75W0qaxs4ZkOSHM3A==,iv:/Kvt2oVKiNS8QJYS3lrpcno+i2ycSMNxuo0CvfhXk9Q=,tag:x+DfaW41J4mbQWsvOVuVyA==,type:str]
type: ENC[AES256_GCM,data:54qwbKQD,iv:YCiUY9oW8jlHhR8mmA/ZAoTwtl89SHZuvCtn6oaBAX4=,tag:bEoRO5NWu3Az4kFJ3Ehl4g==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:VozYXIXBirrjpidbmZHO+Wm1c1KsEuSu,iv:IcQmoVYIL3Au2T3X8YlbC51xCeOJr8ikeKolxucTpK4=,tag:4SlUpr2cjkKoN8hEk/1lxg==,type:str]
    postgres-password: ENC[AES256_GCM,data:jyStOs+dU4DTQIBPNBRZffZLz+LyrqYB,iv:fHPjfr+K/fcTrZyTg/QlVtGG2d+1mhCvZGce4BCCz6E=,tag:xhAmXdQjh9Paf1U/Su8buw==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcEM5NGdjVU5WMHhtOW9S
            SHEwQnNxZTFQNEVNa2dMNjFMVmRraHkva2trCkNqcFhzMjlnUFVNaVZISWh6MGdH
            TndPUkZIRjBWQmVrb1NWdDZhbHdLY1kKLS0tIENrVzFZZDYreTFlVllHS0NpRktG
            NVRMT1l3alEvK0ErcTZMbUMrWEhTTHMKrbQE7Hp99U3ENlu2KQINHLrwPN99P7UV
            n9+skIF4e8t6YjnPPw/ZPOzqlwPmAFlxjTMjt3QTumpmOvA7fdcs7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T13:03:48Z"
    mac: ENC[AES256_GCM,data:+4KawPkWqZyLLCbfDPiWlqAQabh6HklPKyXJz/bIkxPk1U81CfXqhqZBXQZJ7WtkvAN/9M7nruYKKxowiFf5iqVOq/nh7iskwS9R6EBpNPfKAXHe/I+So0WJ5rNKUUFcejuitPMRgDyPSK+tobnPd81wE27DZdHbr+SA66JT5CY=,iv:F8izvWzOXn1mCB6nRfcOAVyAyV+joHJeyvygSAH9MeI=,tag:+/c+nJda6ByfhlGtsihCqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
