#ENC[AES256_GCM,data:05ykDBXqVSwei3a3RKJrq+8Qz5INVbm9xb2907IK,iv:UbBU8HTIJMQFirLFtu5u+I1hY5QlybZh5y3cmYFuMGk=,tag:GcLahkH8BHv64dwUEPqWWg==,type:comment]
#ENC[AES256_GCM,data:jsdltK/AWNEMaCAzoZqdrhPK8oIA1Fhxj/HssgFnbRElTr6b7bYQ0dw9h7FZSIy2UltenbyD/ELD24TycA==,iv:wQX4CXmBXf3Vk+G5gdpOBwiM7/gtdu01e3wh4ukVhOA=,tag:mE6PUl0BQEaDlJFTQK3DnA==,type:comment]
apiVersion: ENC[AES256_GCM,data:3dQ=,iv:onRZ+ff6JYGiTaLKFYRVu5ZTxkmXMPiHMmi11kt0iyQ=,tag:Mf1auBE+UH/qV26GNxj4mQ==,type:str]
kind: ENC[AES256_GCM,data:xHoCU2Ru,iv:a4h4PJQgOOGEOweJzjfAwzXAQPh773uEUwKELpK+Ue4=,tag:i7fkE7lYRhh27T4/cZ2nyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:G1HG0nYrjtoU7N4508hZMD/WyA==,iv:CxLW5/WRLi9i/ilm0o9hyjyWqs/IDO79a0PBlY92prM=,tag:XODTP1Wqk90QlFOycJyuSQ==,type:str]
    namespace: ENC[AES256_GCM,data:YQ5j6CNx3w==,iv:4xd0I/ApsJitrSTf/fB/HtfkVBrStLom940CngpGjUE=,tag:xZGYD5JgogGe/IRFyiyI6Q==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:yqnpwM60pg==,iv:gw+eEFtQVg++eIMBfA2Fxbxtoy/6ZhZVaFBTUdcJh1g=,tag:vNU7cFvfTEsvzQrnaBKiLw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:Q1s3ntyq9N95EZo=,iv:GIP0papjCS5hBWfBe0tb5kVapSJr1jXEiITf1EbeB+w=,tag:v8/GOQlaopzy8sbqUb50YA==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:WBO4Yb/Qjfk/7UFBoCC4/g==,iv:5CHRrDHQgGuMoAAPqKYHaNCFlpc0aTVOEbAHHr1zz3M=,tag:l0eOYBPKCUp5Ah3ZwtKNgg==,type:str]
type: ENC[AES256_GCM,data:U2Y3AuG/,iv:2xchHq/ak2jlQx7E4BVvD+X3+hlsdPnUw1wKMpxVcd8=,tag:hskyO92vF2+gn/CYQuxSBA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:enkiYbYb2fqQFySAa13ziA==,iv:RdfkYf5EUbJcO8lB+hmPd65EvC7gw5cwDmxZIwViFyc=,tag:8Kx8c/1GUJmx2hTJaqotTA==,type:str]
    postgres-password: ENC[AES256_GCM,data:IlWhElQ4J8Cze4/QplFG+cCp3VMzxvg+,iv:lO/lUWe1c9CNRrL2GeUC9zQSfrAge1zmWmG1ppyQZTM=,tag:BROUd8OEWb72GSvtwXhLUA==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkJvd09FUFhkZHZFWFJo
            Qm82cllpeUdmRFpsQm0xL0VyR3hyUk04V2xvCkxXRTNzZGMrczZPS2JpbkpBckRz
            VWFseWZ6T1dsa2I3WHpqcDZnRGtIazgKLS0tIFF1TWErRC9XeTg5VE9ka24xQm5V
            UklONndwc2NlbitlMElIZXpvZjI0OE0KlXmAP3bYaoHQWGrBJ1twgcV94pwgOsUe
            Ufx+uLfmZ5GTNc1NfV0U9grZDey7zq2dW4/ev5+C3ypihV5nEXSuew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:18:03Z"
    mac: ENC[AES256_GCM,data:3/NFPQXvh6Cq4DDgI43q/hDtYKTSYYKScfYTbKVB5uZMXCfkJm7TD/lMEyL2YRbCZbnIqyLg5AITyNXfE+YfiR/hryoDZuDfJcK8fkSARoCJG0ytzYeMTw7KpVu9+pfttli7QwM77LNcy0tI/pbzNdAB5k5AkdLcr1CYuayt7nY=,iv:+p6b3m9KPr8dfk0GvkbCYe9vPBi1vT9KBdd4XQexrS0=,tag:Uy8FzMcuKkSxVwotdLYGjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
