#ENC[AES256_GCM,data:FeRXZv5XZByrbNFxgJwfMKCq7fWyYNjxL6k5fVC4tA==,iv:saUcAlWJi6C/Objx0l6VnnIArBIGMfEDQLLHYep1d6A=,tag:dPiASrhaJatsYEQUSP8+og==,type:comment]
#ENC[AES256_GCM,data:xVlrw9dfcnFkz6mEP6rSWLe73RTbuRskPflftU2J5BwD00AlRKeMWEye3LOuq5g6AIOpTr/RQ8/ADub2ng==,iv:9HL6YOZYvjstpd2TVM/+iM5h67THi+wIFkZjtzG7png=,tag:hRfRNCE4LocjBphheEVvIQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:Qr0=,iv:xH0lQ0j2+T5TPrxos+dQ/z98Bl/PWZondUT8BCBkp3g=,tag:TzKDdYbSfIBcSgU5fr2MYw==,type:str]
kind: ENC[AES256_GCM,data:s9euCcyl,iv:be2iMhFdyZLsd91skF+dKwLQ3daiCO9kwd/p7O4vl2k=,tag:dsSv2XW8/mxAu224GXFIHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XB7d2cmIdeZqgv4LaNW+2dU=,iv:n4/p4fty26b51k2/Y6RpIHI3p5M/PzB+pqbmAEdTBg0=,tag:cqaA7Gl1ONJsTHN58iry7g==,type:str]
    namespace: ENC[AES256_GCM,data:cnvO5w2w5g==,iv:lUgbH3ZHo1/IXyfQVOw2ImyVl5l7AG2xtuSlg78BA0Y=,tag:/kWLfQf1vh2DmJzz+o5iYQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:p0EPCrod+Q==,iv:5nmif0l8nWU74rBIUbDL5rsH1qMDDEVyLE8fFerr74w=,tag:7FAnKMEGaEaflfYISxkoPA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:XSI09R4IcxgIBA==,iv:4HDF6hTF9p0VHNtaIyH6zsW5pv8C3xbq/rKoRogspF8=,tag:cPFClttxM2OXI+jShJ60eA==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:ohmsXxqRh9q0jPlSUUya7g==,iv:YYNl84WsmvKKgEGgn7Yga7TtlWbJywz2z8F5fqfCViM=,tag:+rGV+QvBWprR2zPXAvZqMw==,type:str]
type: ENC[AES256_GCM,data:ybPPLMOc,iv:Wa2EeeurJl3aog/li+k9c4GnKKYXc9UHx2xACcaPGT8=,tag:PsN7bxduzF1lrg8sa2228Q==,type:str]
stringData:
    users: ENC[AES256_GCM,data:qjSB1KF/2AioH8EoMlsilhqhwJJLof+ksVpAGfVd4idEfDz8mqhQ,iv:VJUtsfEBolrzM3O83k0Uh3dei4nTB+w6f4HSL0/ktwE=,tag:DqumU4EaybqgI8+TCRy2pQ==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWjFJTHh5U0hEdGxmTk9G
            dG1GK21VSXNrOE9LckRRc3l5QlkzSlZMOEd3Clg5am84MzNjNVBkUEtheXc5Zkpl
            bzNhYmRkaytXbHY0VXZYTm5ZeWhncW8KLS0tIFl4TVp1LzNDWDR6a3R1WmlhbEQr
            c1FIaWUyMU5ZaHpYRGVhVTBXUkJWdjQKwzupcLbS6lYw8RTiVgaV37qaxYet2P97
            5ydLntLUB3L7NUGRwsYXVHUFTje4tX4SvKTUusc31zz9ECcLJgbEfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T22:42:03Z"
    mac: ENC[AES256_GCM,data:CWbeMAnpWtieQAlI1HNUXqo5gs2Ekgm8HzG9UCYgT5UXGwlUeaLXbX5hhnC41lm1KhKCfG3K8eGsGLk4j0XYb8lJlnJSNZPwVyaFBeCcEBfRgIn2OrL7vidEkUZKNpheVzUeNz69k5QxHAPxaO9vq0AsFigoaAhBxUK/Unq8evU=,iv:5lTwFOxTYasGeKUn6jn0x4w+XC6waxzeAWcPcxWvOyU=,tag:FzEYUKgzZ/dHdewkXAf6kw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
