#ENC[AES256_GCM,data:gVZ0czTcBEitRpkwFfmfHzUbS8wpPriI/+b/mzVsTw==,iv:TTqO9n7ibtCbKv/41yAcrpnJt2kl2FZfQsUyCBlseyQ=,tag:gVXg6CdM/R9q0Z9FfheV7Q==,type:comment]
#ENC[AES256_GCM,data:RmZhhNGBjRHonwVyGCpcpBiKe8Z30MrvwQHaJ4vZmLdgbrJkYaCSmtD5zyXvUghrGomzqcvTa7EiAbceyg==,iv:WvkHayjJrN/N9Wn6ALubF8JoyRxgqWn/aNEd+7nWTn4=,tag:37yx/o7JX+HbE4Re9X1zaQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:3a8=,iv:+w+oi2kOeO1RRFFiuxaHjo0cwwkFnrsegIl9c5UDmwM=,tag:ky4KyBO8/TQvCVCeNIf/Gw==,type:str]
kind: ENC[AES256_GCM,data:H0ZjAaJ/,iv:Hp4IGTGPrVnx6Z4+TcpMdaiYzXX41lsS+vM1T89GAeE=,tag:JgqAXvAwKYbyO/DG2EUweg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TdDRPJq4xI2yN0WIPTR7BH8=,iv:Rpt3QZtAepjO2DsNAiI/i5gUR3yWtNfpKoM/eh3iRUI=,tag:YK+uKzOw615ginb7kbWPqw==,type:str]
    namespace: ENC[AES256_GCM,data:MkRs5ZbxCQ==,iv:O9MAe+jqWfVgNquxS+T6eqSC7zO3Hund/vEyatr4Ydc=,tag:ahu49ZRKmHbvyi55aCsz3A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:mbBx/1jhOg==,iv:VtWDDuIedHCedO84Fo2rJ6WmscdUWUE6AmtGxZbJoYg=,tag:7X7NsOuGbYGGL+PUyUH2IQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:v5nysl445tq+TA==,iv:cXsqePyfZ/cgt7PNBuv8rRg2qr8BlFx/0bhlYa+76A0=,tag:bSMFe5z9YipkvR1qj/QuPQ==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:PE7ec1k1RFqMla81Vy3UOA==,iv:Mc2MsWZLGp0YnT221zkYl38MCUsn0GMD/msV6gLOJcU=,tag:6XHHJHdR8X8yfGsfKSkJWA==,type:str]
type: ENC[AES256_GCM,data:Od3ngrWx,iv:EBXaF3tGFUAEK2T5u3RxwNsDomUIKhe8333+mWAbCrQ=,tag:WG2U19SRCc365Bnfi+1Gzg==,type:str]
stringData:
    users: ENC[AES256_GCM,data:plBldtF96qivGs8odrgf9ANv6j0ZzofMICu1s20D5lgUR81sSsEp,iv:9EAJy6K97MVUjNoL0ZPE9eFNZj1rkTfxAj8UUb37+Vg=,tag:Tgn27rqYhYcG3yPU66E+OA==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ2ttWVRKOWtWRzkrclJu
            TStkQ0h0dFFOUTlEbEtRN3ZaTjhPOUNXZFJBCnFvMkZrSU9TUnhpeGtpRm1YajNI
            VUhCa0h5RHJGQnI3MG9iZHR0bW1kbkkKLS0tIElIYjEzcVdGUk9RL1lHVE01U0JZ
            V25CbEtBVVJiMWdsbExOdGR3NHdkRGcKRSLvUe1oU1g+YNhkpTaVgHcEvvt9Nggs
            J/W/xRctwiCSr/BPYE8W60NbztppxuDPiL/5r/n9VzorSdjs+TZU4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:52:37Z"
    mac: ENC[AES256_GCM,data:EZAVF3NJapWRWnaNsNfXv8Bpew9I/kzr2z3krFCcqaVFZwYsfi00xlWn5qtowZ7RbaYPv4bLd76Wu9H41klCvk5j/DLX+c9vyaSszrIKZFumASZzuY/xjpsT8wUz/Ba49l0aYbkrHTdxaZCVvQZkpF/aqcaGBGyTe8CTABA9G5w=,iv:G8OO8Sn6Cn/HDWzqcr7UJjW7n5w0Mi75dYDKGnTLNS0=,tag:6r6ypgaYYsDC7CpQVxmAgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
