#ENC[AES256_GCM,data:LKzAIMFe/FSpdZsz1imLbodecSui7HM5L2jgLoklwA==,iv:kZc9v7CyxDvhPNS0z0n+1JfhwCDBa0dOBvLBAzBkL2Y=,tag:6Xguz08CPgWK8n1S/Y/udA==,type:comment]
#ENC[AES256_GCM,data:Bq2pVl3hTx2sJdpsbAIj7Y0CDVjnaStk2rQ4QM7EqQcokwvQH1715ubwfTtJJECcV+zsdW+109aj5VNljw==,iv:QPnN7INMB/Wi+ye+HDS35bdZpK23w6yxvUsxroV3jYk=,tag:2sZWP+3jtnq9hAjCSHofcQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:rtY=,iv:8SJxPSuyCMfLhiMZXvtU62R+HAyytF5cfm5mEpzymM4=,tag:qstoTpOx/4JG8XZdTFRTyQ==,type:str]
kind: ENC[AES256_GCM,data:08fXpOxf,iv:RrkyEWEx3UUHbpQoiHaDcqhrX5xR99mT9pgGKzl0qIc=,tag:Z0r18zi/2orLsXt+8IOHTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lHZhmueNLcoKN2u7AfvEXYw=,iv:OhODXW/PUDcyyLt07V6sP/kUq5AyxNUlba0ktc1uER0=,tag:Ma+tpGGBnE/Cf08uKE0/Wg==,type:str]
    namespace: ENC[AES256_GCM,data:PaWlHxFMzQ==,iv:Tcx1pnTl9D1pAm1g1Z11uUjgODWXsbGZzcCwacS1Af8=,tag:92wXIciuVRY4l0TN6pIt8w==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:p1kIHC0GLg==,iv:BCOA0881C4wDPj5/lIYkZyzG8zfo27MSyXLueu3n2hI=,tag:P+oNNtDKdJJJWVUR+vB9LQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:uwL1QjdRW+f1Uw==,iv:45RQpgx2bWqNwi/z/KkxPvycSl0f++LJI1P7UIywurk=,tag:3SiYcjQO421quOkPyet2lA==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:SqaM43lguqHKQGHDq2KRiw==,iv:B0mt+P09JU/5WQ6Xeb2H3nKM/ECOF2MGjYxO1GTXWzA=,tag:1iDPgmBuCXs1MacXMZMZug==,type:str]
type: ENC[AES256_GCM,data:ugmUaiE4,iv:OxuIRJJNyWsqDDDapMnyA3fuMFb1eolKxeC9OKTh2W8=,tag:HQ4WWG+jZTXRb3BE/OFuaA==,type:str]
stringData:
    users: ENC[AES256_GCM,data:e/fL5Znp4dWOxSiXsp7BDDUo9bZOZ9Mq5k9OWOwuFZ2gbzoTnWyF,iv:ORlfETAmDuSors4l0RdfbS9JQ0RoADTsbOM9vPbIfLQ=,tag:yQRLcTRXWmoKuxTr/Hi5IQ==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZlJaNVg5N2swS1JEWnFo
            ejhFM1pDZXhSK1oxRStRYTR2d0plak9lTlRFCmhNeG0xVTNvRFRZMlRGNmM4VzVv
            TmVvNUt5ZWlLOUVjU0lBY2VUWlhIVUkKLS0tIG9QNm1oeDMxL1Z4MTFLZGNiaFNy
            ditTbjBhZ1ErU011elljcnhTVFBTMVkKiKvtWtPJrp75gn55gTJrc7xEm55uLWuu
            2EBagx4c4sVbeAnFA8sSul+5OzyaPgGSSeHIdCSuV0/f8vGNN/wGIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:18:04Z"
    mac: ENC[AES256_GCM,data:4hw+Pyf8Ol8qz+EzyOl8oMZZxvsBcEGNlHbdTjmoO4ASKoUVUTFaDsPBvdoYVHkBmM2yOUxpk9Muye9cNpoql41jTdPUFR4IDmPqrAM1odKhnTZqq6lZhbObAxEUUpStVDdA/3KBm2BUwvZzhJT9HDR8chSbQyqvjpWuuciLF0E=,iv:alnErzwWlcYeRprzTg7A6IxuJoMT9t40aprcyHWfJy0=,tag:CAexZJOjmSW7p9B4ENgYoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
