apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-data
  namespace: clamav
  labels:
    app.kubernetes.io/name: clamav
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
