#ENC[AES256_GCM,data:xKhXfKGilzcVI7tSjaVKcfdMdId7aGD1h0NLfspSt/RrID802Gp89A==,iv:17iQhonXjaHYpRE+Zc1j7tt6+Ba5p7CtCmCikz9Ywkc=,tag:8vrNH9LN5lmWnnvAHsh2Bw==,type:comment]
#ENC[AES256_GCM,data:bKyGH47p0cgox1zkjRWh0Sk+e2svBoa3s+FqPLWF8RwN7j7umaa8jSSw9ZDGyTM6metuTXnCIiCvQJjaEg==,iv:N9nub5fASzEVLHYM02BA0YA6lsemawZ5qrIv5ukmgJY=,tag:7KR3o01niEoCWrbavL5S/w==,type:comment]
apiVersion: ENC[AES256_GCM,data:JoE=,iv:H/cPBeJux+IkCbzw9DLhV9eXkigUjN3JN5qoExrKTjA=,tag:rKXBu+C+PLBosmgI9/hX5w==,type:str]
kind: ENC[AES256_GCM,data:eFDlp6Mk,iv:ZFQto+jgmcf/vO7YrCG/SIuxgesoMj5eBq3+JFrO5Rg=,tag:E/8+/2nVw1+sF9tGu4mZzQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9DWSatkDHgJIH2ifFHT3kniz2adXK3uwNA==,iv:kFtPFw9h7WPT8u3nk0Co4mU0OkLRrx3kg+MXjZlsR5I=,tag:Dse86fSAGQEHJIhFtxxAMg==,type:str]
    namespace: ENC[AES256_GCM,data:KursoFwqqjsxGw==,iv:J5JVcDib69bNgD1n196WIs4gYU51mpyz0VSFt6e+sgc=,tag:qaxu2y4cCP2/odTguNWSAg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:bPqFc1RLDtsdRQ==,iv:iPbhLW6SZVyXMlDR8dtc2h2TpJfkkOsL8bxq7d2hpyY=,tag:HjvULcFBTX4M7ZU+I2yM6w==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:skOkg+0uJ6xkHAc=,iv:t9AkLwt3sbLG5PyOpIX3jxJ1CFWgkFGxWKxFM6DLdBM=,tag:aqqlNtYxnhWts4BWWIhwwA==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:UmWZZzUpNTPi8J4grPVrHA==,iv:2OFUWuxZBMRurkb/Yg0cx7DxDejlo1sYUjWCBXFmH/0=,tag:NQdP9xzYbr4PDKxSgRA2RA==,type:str]
type: ENC[AES256_GCM,data:k0v+Ut0R,iv:Owy1XsTjngaMvZdujoelbZzaSn810MVHbH1/+WjxBNI=,tag:FT82tFfePSQJ8UjwwL+HWA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:lj3a0DuIjr9ArDa5u399L/iSjOGzuF5I,iv:5Re/S+w8H94cIRNPvXni1d4UvdftPkhBLt9P6JpCCCw=,tag:dAOMFpfzHR7c8Azx9foxLw==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YzBreXVzN0RsTFVXYUMz
            Yk9Gam9pam16V0RpRVFyUUUzdWpHb0psbjBzCnV0bkZORXpYTUd3Z0EyQlJCblV5
            bGs1MWVtSkVrUVY1S01xeFBvZHpDQTAKLS0tIFFldHFMTjluQ0NML1RwbDAzRURF
            U2FkNEdxR0s1WXpKYmIzb1lySnJwbTgKlT6XSXd/ZPLZHGlC2RdvPChl+yyy+Dag
            +0Juu9d0rMVYgal50CwafNwtei1LDOWVi04ltLOlSqb7v3wQQ9NL/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T20:34:37Z"
    mac: ENC[AES256_GCM,data:rwF+3/Wg1LwnaXDTNX703Xi+anVP698HdGzqOkv0S8tKsrC7y3s9AIwiWmwAtkIi1rptXKXyEU+TFiJYOMBBUR2d8AsBTc+CpYEPdgp1UuSGsBfl9NLDDRw+hdh0XZHD/PjVDTzVPYo9P/Oq5+C/8RJo1Yk9vJ0tFweY+MU0BG0=,iv:5rvY+QW6W8YwxAkHUp0K7XHhSSztcIBt8IbXwvto+Rc=,tag:MIbiqtGpx83hK4/BwTi+4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:qnY=,iv:/622KOEZCg/KXozrTN0D3UAlwcBXVZt6zveA5uQNS8o=,tag:8hixWEgzLbC1vKKriHYwJg==,type:str]
kind: ENC[AES256_GCM,data:6QOSJg+i,iv:U4T9Dkv75HOmQba6F53zHtFHz684EozsNxIimHwXFeE=,tag:iTQpRFUEawmrdOsZa2G01Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gYGPqXkdbdDo24vDQSJKLalNIx/tg2ZvGaI=,iv:1arUJbshA9ZNZbIu/6ExAe07SYOFWQCgQw3kM+kdWUM=,tag:ogYILrM/h7lNXUisRdzBWA==,type:str]
    namespace: ENC[AES256_GCM,data:YlkNTLTLVlsdew==,iv:dtzcmgN6MmcjHYc2+4YIBoeOYj14NopOh1DSBf5JiGk=,tag:5JbsMJwyoOR6xb9QlGR74g==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:vlai8iWhasNKvQ==,iv:qhYurYuELkYgMFy9egF2yURpZRvins1wJ7yCyJnhYi8=,tag:Vo4ZZtlZEod69lpBWYTVzg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:uiYokLTMzrIL4o4=,iv:vedGiBGAbhy2+jwxtcgnRgPJCcG7jHdT3ft7AP+s59Q=,tag:LsFe+zNe6iIh5yCTLchOBg==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:QRhIx3qE7JYjRgwajKVeNA==,iv:45dYSz0gmsEoKMZB3RPir5AZwjTZnxohc4JNfYLGeF4=,tag:Pywo2FV7XvsIG1cIycfZXg==,type:str]
type: ENC[AES256_GCM,data:MI0MR08b,iv:+rct9lLeOz5Cf9+amPkbUXLjyKL4ObBF79PF/DWBSlA=,tag:HUd6xb6/5PvzBE574+wS7Q==,type:str]
stringData:
    password: ENC[AES256_GCM,data:0F5JKL70waDLkBdV4f4lARD47hjE83EV,iv:TEd1z8/pRxT6x6S6UT56sKN0wUZfwbLS0p3I9iTh1Vo=,tag:X8Q+yJZSNuyTxxNCT6Uqew==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YzBreXVzN0RsTFVXYUMz
            Yk9Gam9pam16V0RpRVFyUUUzdWpHb0psbjBzCnV0bkZORXpYTUd3Z0EyQlJCblV5
            bGs1MWVtSkVrUVY1S01xeFBvZHpDQTAKLS0tIFFldHFMTjluQ0NML1RwbDAzRURF
            U2FkNEdxR0s1WXpKYmIzb1lySnJwbTgKlT6XSXd/ZPLZHGlC2RdvPChl+yyy+Dag
            +0Juu9d0rMVYgal50CwafNwtei1LDOWVi04ltLOlSqb7v3wQQ9NL/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T20:34:37Z"
    mac: ENC[AES256_GCM,data:rwF+3/Wg1LwnaXDTNX703Xi+anVP698HdGzqOkv0S8tKsrC7y3s9AIwiWmwAtkIi1rptXKXyEU+TFiJYOMBBUR2d8AsBTc+CpYEPdgp1UuSGsBfl9NLDDRw+hdh0XZHD/PjVDTzVPYo9P/Oq5+C/8RJo1Yk9vJ0tFweY+MU0BG0=,iv:5rvY+QW6W8YwxAkHUp0K7XHhSSztcIBt8IbXwvto+Rc=,tag:MIbiqtGpx83hK4/BwTi+4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
