#!/bin/bash
#######################################
# generate-secrets.sh - Generate Kubernetes secrets for Talos CleanRoom
#
# This script generates secure passwords for all applications and creates
# SOPS-encrypted Kubernetes Secret manifests.
#
# Prerequisites:
#   - sops: For encrypting secrets
#   - openssl: For generating random passwords
#   - python3: For generating bcrypt hashes (ArgoCD)
#   - htpasswd or python: For generating SHA hashes (Traefik)
#
# Usage:
#   ./generate-secrets.sh [--dry-run]
#
# Options:
#   --dry-run    Show what would be generated without writing files
#
# Output:
#   Creates SOPS-encrypted secret files in each project directory
#
# Environment Variables:
#   SOPS_AGE_KEY_FILE - Path to SOPS age key (default: ~/.config/sops/age/keys.txt)
#######################################

set -euo pipefail

# Colors for output
readonly GREEN='\033[0;32m'
readonly BLUE='\033[0;34m'
readonly YELLOW='\033[1;33m'
readonly RED='\033[0;31m'
readonly NC='\033[0m'

# Logging functions
print_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error()   { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# Script directory and paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECTS_DIR="${SCRIPT_DIR}/../infrastructure/projects"

# Configuration
DRY_RUN=false
PASSWORD_LENGTH=24

#######################################
# Parse command line arguments
#######################################
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [--dry-run]"
                echo ""
                echo "Options:"
                echo "  --dry-run    Show what would be generated without writing files"
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

#######################################
# Check prerequisites
#######################################
check_prerequisites() {
    local missing=()

    for cmd in sops openssl python3; do
        if ! command -v "$cmd" &> /dev/null; then
            missing+=("$cmd")
        fi
    done

    if [[ ${#missing[@]} -gt 0 ]]; then
        print_error "Missing required commands: ${missing[*]}"
        exit 1
    fi

    # Check SOPS age key
    if [[ ! -f "${SOPS_AGE_KEY_FILE:-$HOME/.config/sops/age/keys.txt}" ]]; then
        print_error "SOPS age key not found. Set SOPS_AGE_KEY_FILE or create ~/.config/sops/age/keys.txt"
        exit 1
    fi

    print_success "Prerequisites check passed"
}

#######################################
# Generate a random password
# Arguments:
#   $1 - Password length (default: 24)
#######################################
generate_password() {
    local length="${1:-$PASSWORD_LENGTH}"
    openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c "$length"
}

#######################################
# Generate bcrypt hash for ArgoCD
# Arguments:
#   $1 - Password to hash
#######################################
generate_bcrypt_hash() {
    local password="$1"
    python3 -c "import bcrypt; print(bcrypt.hashpw(b'${password}', bcrypt.gensalt(10)).decode())"
}

#######################################
# Generate SHA hash for Traefik basic auth
# Arguments:
#   $1 - Username
#   $2 - Password
#######################################
generate_sha_hash() {
    local username="$1"
    local password="$2"
    local sha_hash
    sha_hash=$(python3 -c "import hashlib; import base64; print('{SHA}' + base64.b64encode(hashlib.sha1(b'${password}'.encode()).digest()).decode())")
    echo "${username}:${sha_hash}"
}

#######################################
# Write and encrypt a secret file
# Arguments:
#   $1 - File path
#   $2 - Content
#######################################
write_encrypted_secret() {
    local filepath="$1"
    local content="$2"
    local dir
    dir=$(dirname "$filepath")

    if [[ "$DRY_RUN" == "true" ]]; then
        print_info "[DRY-RUN] Would write: $filepath"
        echo "---"
        echo "$content"
        echo "---"
        return
    fi

    # Write unencrypted first
    echo "$content" > "$filepath"

    # Encrypt in place with SOPS
    if sops -e -i "$filepath" 2>/dev/null; then
        print_success "Created: $filepath"
    else
        print_error "Failed to encrypt: $filepath"
        rm -f "$filepath"
        return 1
    fi
}

#######################################
# Generate Metasploit secrets
#######################################
generate_metasploit_secrets() {
    print_info "Generating Metasploit secrets..."

    local db_password rpc_password
    db_password=$(generate_password)
    rpc_password=$(generate_password)

    local content="# Metasploit Database and RPC Credentials
# Generated by generate-secrets.sh - DO NOT COMMIT UNENCRYPTED
---
apiVersion: v1
kind: Secret
metadata:
  name: metasploit-db-credentials
  namespace: metasploit
  labels:
    app.kubernetes.io/name: metasploit
    app.kubernetes.io/component: credentials
    app.kubernetes.io/managed-by: generate-secrets
type: Opaque
stringData:
  password: \"${db_password}\"
---
apiVersion: v1
kind: Secret
metadata:
  name: metasploit-rpc-credentials
  namespace: metasploit
  labels:
    app.kubernetes.io/name: metasploit
    app.kubernetes.io/component: credentials
    app.kubernetes.io/managed-by: generate-secrets
type: Opaque
stringData:
  password: \"${rpc_password}\""

    write_encrypted_secret "${PROJECTS_DIR}/metasploit/secrets.sops.yaml" "$content"

    print_info "  DB Password: ${db_password:0:4}****"
    print_info "  RPC Password: ${rpc_password:0:4}****"
}

#######################################
# Generate Faraday secrets
#######################################
generate_faraday_secrets() {
    print_info "Generating Faraday secrets..."

    local db_password admin_password
    db_password=$(generate_password)
    admin_password=$(generate_password)

    local content="# Faraday Database and Admin Credentials
# Generated by generate-secrets.sh - DO NOT COMMIT UNENCRYPTED
---
apiVersion: v1
kind: Secret
metadata:
  name: faraday-credentials
  namespace: faraday
  labels:
    app.kubernetes.io/name: faraday
    app.kubernetes.io/component: credentials
    app.kubernetes.io/managed-by: generate-secrets
type: Opaque
stringData:
  postgres-password: \"${db_password}\"
  admin-password: \"${admin_password}\""

    write_encrypted_secret "${PROJECTS_DIR}/faraday/secrets.sops.yaml" "$content"

    print_info "  DB Password: ${db_password:0:4}****"
    print_info "  Admin Password: ${admin_password:0:4}****"
}

#######################################
# Generate OpenVAS secrets
#######################################
generate_openvas_secrets() {
    print_info "Generating OpenVAS secrets..."

    local admin_password db_password
    admin_password=$(generate_password)
    db_password=$(generate_password)

    local content="# OpenVAS/Greenbone Credentials
# Generated by generate-secrets.sh - DO NOT COMMIT UNENCRYPTED
---
apiVersion: v1
kind: Secret
metadata:
  name: openvas-credentials
  namespace: openvas
  labels:
    app.kubernetes.io/name: openvas
    app.kubernetes.io/component: credentials
    app.kubernetes.io/managed-by: generate-secrets
type: Opaque
stringData:
  admin-password: \"${admin_password}\"
  postgres-password: \"${db_password}\""

    write_encrypted_secret "${PROJECTS_DIR}/openvas/secrets.sops.yaml" "$content"

    print_info "  Admin Password: ${admin_password:0:4}****"
    print_info "  DB Password: ${db_password:0:4}****"
}

#######################################
# Generate Traefik basic auth secrets
#######################################
generate_traefik_secrets() {
    print_info "Generating Traefik basic auth secrets..."

    local admin_password users_entry
    admin_password=$(generate_password)
    users_entry=$(generate_sha_hash "admin" "$admin_password")

    local content="# Traefik Basic Auth Credentials
# Generated by generate-secrets.sh - DO NOT COMMIT UNENCRYPTED
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: basic-auth
    app.kubernetes.io/managed-by: generate-secrets
type: Opaque
stringData:
  users: \"${users_entry}\""

    write_encrypted_secret "${PROJECTS_DIR}/traefik/basic-auth-secret.sops.yaml" "$content"

    print_info "  Username: admin"
    print_info "  Password: ${admin_password:0:4}****"
    print_warning "  Save this password - it provides access to Traefik, Longhorn, and ArgoCD dashboards"
}

#######################################
# Generate ArgoCD secrets
#######################################
generate_argocd_secrets() {
    print_info "Generating ArgoCD secrets..."

    local admin_password bcrypt_hash
    admin_password=$(generate_password)
    bcrypt_hash=$(generate_bcrypt_hash "$admin_password")

    local content="# ArgoCD Admin Credentials
# Generated by generate-secrets.sh - DO NOT COMMIT UNENCRYPTED
# Apply AFTER ArgoCD is installed
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret-override
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: generate-secrets
type: Opaque
stringData:
  admin.password: \"${bcrypt_hash}\"
  admin.passwordMtime: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""

    write_encrypted_secret "${SCRIPT_DIR}/../infrastructure/argocd/secrets.sops.yaml" "$content"

    print_info "  Username: admin"
    print_info "  Password: ${admin_password:0:4}****"
    print_warning "  Save this password - it provides access to ArgoCD"
}

#######################################
# Main function
#######################################
main() {
    echo "=============================================="
    echo "  Talos CleanRoom - Secret Generation"
    echo "=============================================="
    echo ""

    parse_args "$@"
    check_prerequisites

    if [[ "$DRY_RUN" == "true" ]]; then
        print_warning "Running in dry-run mode - no files will be written"
    fi

    echo ""
    generate_metasploit_secrets
    echo ""
    generate_faraday_secrets
    echo ""
    generate_openvas_secrets
    echo ""
    generate_traefik_secrets
    echo ""
    generate_argocd_secrets
    echo ""

    echo "=============================================="
    if [[ "$DRY_RUN" == "true" ]]; then
        print_info "Dry run complete. Run without --dry-run to create files."
    else
        print_success "Secret generation complete!"
        echo ""
        echo "Next Steps:"
        echo "1. Commit the encrypted secret files to git"
        echo "2. Update deployments to reference the new secrets"
        echo "3. Apply secrets before deploying applications"
        echo ""
        print_warning "IMPORTANT: Save the passwords shown above!"
        print_warning "They are only displayed once and cannot be recovered."
    fi
    echo "=============================================="
}

main "$@"
