#ENC[AES256_GCM,data:ICe3IWSyKTIU/HRzgRq4eqOGRalRoeO7K6j8,iv:lDtXRDbRJ3WPD0jBbgqGlqqtKOvaEoXPb3tDuioH8HI=,tag:734H9LJ0DbrPzETNMnS7tA==,type:comment]
#ENC[AES256_GCM,data:zyevI2EpqVU/aSmHwy1AVqeQvCywnRYblD7X7E7y3XHme5I0mVez9Dh/5zb7eFrj6CW2dVfomBTN/3ip/g==,iv:Q7Sbc5Ii5oynArueAZEmGmTXm+dEIe+AUvTSYtshLTc=,tag:QfTBX0/YQ5wt3QjLZ0DiBg==,type:comment]
apiVersion: ENC[AES256_GCM,data:vGc=,iv:tYr4OPXu112f+fDgcXcLsi7jGVozfyymTMxZxxpMYEc=,tag:EgXqzNkhwYYltS8oM0Racw==,type:str]
kind: ENC[AES256_GCM,data:WZxKpLXj,iv:SesrG8kt0BfVGFRh2al4kLk9UJ50PVF+zjXW5eR3SRk=,tag:+szoD5mIgMiD8gtk9TtfjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3DlRNdlI19Qoo8fNOmpoMKS3,iv:dtcwpWAsVPm6TNEItUTPIaRFjAS1Ln6U0tHjlqsBhIE=,tag:7C1gzTvqMROhloA1b4tU+w==,type:str]
    namespace: ENC[AES256_GCM,data:ZPnTNJQe,iv:SLLtAWGe0/gNS+g1ZBci2LCrwYgjtEpCYDQMbzbxeUY=,tag:vJZlvyJOPpY8zIoM18ImLA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:q+qXg9aP,iv:R0qetaFLlPNslMVX5ZoFA6wsC4YhS3EtlZUK0ziK8Zg=,tag:f6AAPiFx8AtbtWZlYRX6uQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:jqaz+HcWPOFXKg==,iv:Ptc9Y+SoGX1oPz+v08v9b+53dHh8OIbTCBpKHzAmZ24=,tag:kWkinQT6CTv1Fg4E5yu7zg==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:4dQKN03p61xzvSQi6EdjTQ==,iv:SN1OOAJ85+V3QJD618U38oCTdXwcOdA3ALhKf73P2U8=,tag:OArPivp64XEGZIGW+6DbCg==,type:str]
type: ENC[AES256_GCM,data:tlgn905T,iv:trAn68mhl3JoAOfeMBUYq08E27akyPlxp43ze5O26IU=,tag:PWOtFUc6CpxuEeX7PPwNEw==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:8G/Z3bS+cBZiIBaWd8Khlri5VfHOC4Vr1+rcT7oEkfFyKQ9xhPnXIDyzj6YcJWqJ,iv:Q9vyhuz8O4I4a+Ou7RLqUHT/UMGFQdbFhRB3CvjL9ro=,tag:kUujeqSuEj0Sxd3FqWLmRQ==,type:str]
    admin-password-hash: ENC[AES256_GCM,data:bzJ6PbySXC27M+OGk/Q7FySf/NgQMrLzkKNwfl1kdUGanCgCfWAsg4O3vLyvS2PXnRwL6mnt5triJWth,iv:CHkBE8QnuDUBCKKUD/UA8eIHjMVKA4x72Ii5fQJrVA8=,tag:dXAfdQ4y1tdpNJQac2gfPw==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRGN5OXl6SDZWcGNXSC9w
            dkpNRGtIQ0xPU3NDM292L3Y0YzZYODVFODJFCmRRY01SamJ4Skt1VjJHM2l6anJQ
            TmFwTmJ6TWYxN015TnRtdkY1dHZkeGcKLS0tIExBUlpKcGYvaCsvSXBrYk8xNko1
            eHJoSURPNTE2VDdUTkJiSTBaZUFpS2MK8e287mil66hwIIiZEuPmR2+Hz5tPPIbO
            pF7svQDNhir3pYfKa5pvcuIdramOTOjmSZ1QA6zSsYpXQhkOF7ONhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T13:03:50Z"
    mac: ENC[AES256_GCM,data:a2wtXBmsHNs02ppOYH5C/3F/AvdFYW/unMp/iltmevoV9Mcw0sYM8wOFKxhnJKLsrr1SPoSXfI3qzYnqz/GDg+pp7rO3dbjt0LcmM5Qsz/t25UGztOFidmHRhXfG37NfGyXIiDiw8iUzPURjkf7bFIgVN1uVyWhBVky51rJk/4Q=,iv:c5inGBN9mPx3gjkhtcXj7aQXa4Q6nalIGWaM8J+kiu4=,tag:BDouIMRfUfg41xF4KqB0YQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
