#ENC[AES256_GCM,data:SmI83u1XFoVKTNxKrlWIn+IOS13lu2dEOHxr,iv:YUASGg/9lbnlSNv2yQfcq4VFZbth3yytT9nvt7xroqE=,tag:mLYfmQeRmDD6jyNHO1DDrQ==,type:comment]
#ENC[AES256_GCM,data:JqsTj8+7NAXr8w0vfXmPCtqFKjoASlR8N0rAkYy5X1iVmR/EBp3/dlgdzWwvixzZCZi/VGgKmASng+TLWQ==,iv:XTR5eg5rGOjMuYHcatnPVcKclt4Em4DSC964L34vnNU=,tag:HRr1OtUO69ffbyBL9NwEew==,type:comment]
apiVersion: ENC[AES256_GCM,data:RJo=,iv:IcuKLOPGYdDIaYAUZG6iLLhXy+ItBz7LmKFeLmkvvak=,tag:kE6MAPen451IdOQrvsaoUw==,type:str]
kind: ENC[AES256_GCM,data:57eCEh3n,iv:wRqlgrjjBB5v5iP8+UGiBvhtHviJvvhEOOqGrk3tQ+w=,tag:ByVvaDxMOE8KhHDIDN/NQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:C/T3oanhKU2wMKVWhCIT9w3G,iv:wewqxehR7p+rIjKTQstPSdYK6V8OO3yMpdVBOAYA8L4=,tag:18ORqZUzf0wKtyxssic39w==,type:str]
    namespace: ENC[AES256_GCM,data:W6cTWpGv,iv:AOav2x4quYPMpJDuyHPuhPf2Qqt5ls8PDVVGFN2g71s=,tag:AkBOHnxYRzwakR2VZVm4nQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:kehoppN9,iv:/KgKVnU4t4aKpkUClQs+sPUBwdyiQ7u0bqlT9UhiIUU=,tag:hQ4lhmccn7OvMwyCX0QToQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:vOnEVJcHD8Fa4A==,iv:+8y5rmi0DmpWwsOqh/WaU7A2PxPNGqqg2L0F/NnFkTs=,tag:J8FcG/NjvMRegpj1/y2yOw==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:+x+nOaBy+ZsQAMnyr8plXQ==,iv:wD1X5Bp9YtMb+5rO9aYSTfcojsIiQwVwYBYRUncJul4=,tag:s7YqLCVkkbGsiv/kp5zzcA==,type:str]
type: ENC[AES256_GCM,data:xqqTaQlV,iv:Umx3QgS8cBBduIkuXQwFHyKvikCNCgeapA5haMQLsuU=,tag:6Ngo4MCvMYVmfuv5ZH0XxA==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:sR6kvlB/SPBAkQ7CyzvTzV7IZLxnVL4KHCKQ304te/njecOIaW/755X7UTN7lNWS,iv:4WLapU5r4BjVypjYtI848Oodm2l3IigYhEzN/oKENGA=,tag:+4A/FtcCxhu2pw0kdhBDXg==,type:str]
    admin-password-hash: ENC[AES256_GCM,data:9eb0er2G1JLLziNXh13/0NYOZVgJpVWeygI7l5fAMroY9c4ZHZ+IZoqLgScZ8of7cbj7luIPZiiIc3us,iv:eXokL4tHStSQBxj1A/xz9ZEv+34GQ9nJG2GiabgszY4=,tag:gnh0PlyAadbL4m6dsdSa6w==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM0VKQ0dzdVFmZktzRGR4
            RHBnQmFkdUpFaFE1c0RiNEt4R20vSTBTMkZ3CnVxZHhqbjNrdWI5aU1UbHRoTG1n
            RmdnRGsybmFDZ05Zek1Rb2ZqWmRoNHcKLS0tIHhXWmpJK0NJTXMyemQzL05zM0Z4
            MDZFNEdTWS9jenJYUUZCVzJYc0xZNVEKlwDT9nW7Rxc+gS8kZFVzn6mV6ZwHGtw9
            UcYEFDgnrWc9IYEGXfzykKWCWPPlqlT8DKBaxLky+dA7Ncej8wVKCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:52:39Z"
    mac: ENC[AES256_GCM,data:1tPp+5UZOTSz7Ti6vVkKVAV5O8P28D+I06vE4ikJCxUFdioEJNEy4f89/tONpd8z21I+UZu7/u/C1sfrJ6VRHHfGfQjVAwbnKndb8r6pnKESDvr7KMsnmCLzZH4Jmbbs8eA87miAyKIospkIqUwQ+PEgCKPmmSdYQII06RCKWlM=,iv:tqidM/2379/q7YQ5abKnf/NRbeizFndeZWqYpQ8S7p4=,tag:u/Eh+Bn8OS13ONuvMLOxLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
