#ENC[AES256_GCM,data:mdYQo2HlalOGC55AZJzyBdnaQyGPot+ztc8g,iv:J86qL79z7InmKJ60TGZzIWWy54xOhmABlbxDa40t8Rw=,tag:YTPSDu36xXGZBDy3VvAdRw==,type:comment]
#ENC[AES256_GCM,data:kL9wOM0ZySb6sXfl8YtRe68bDg5MPlbvlf/sw9VP+VFGyBqVbNmtKnW2y1mczC8h8lqR/eRWzEj+CyLWWw==,iv:Cz7SOaorizaKWbgBDJ1FEfhmMBkTX0xfWO0bb5VXcV8=,tag:O2lFNsxzBiUoyZMCGfzrFg==,type:comment]
#ENC[AES256_GCM,data:ONFtKI/oDZTtJkC3V/PoGVjb+BE/0xVSIK40mtNAloi+1cIYmjZba+u48omjpOkcPJng45GZULUd6VoCxEnY3g==,iv:71OyonQMsMhcu53alErGVhyFMqCefnp5u1c+QRVhhu4=,tag:4/ZSTAfLx89YiB4MygTUwQ==,type:comment]
#ENC[AES256_GCM,data:sfYOBYwOtkTqVIhhWeZGnzmoghaLPm0+u54Ev3Ia28XOkfioYB/sqK/zHIdPLn9qNY1hyz19aRCrRVLM68Wa,iv:aoq4m94jz5yRLa1PQ6gwgWClvva0HN+VfHDr9RUXi1o=,tag:3t4/w8yDuRRtCXDjD6pYaw==,type:comment]
apiVersion: ENC[AES256_GCM,data:JCw=,iv:bSjbA8/7buN8xlTUapyZYzUGNW2+APTOjm8RxJdN5sQ=,tag:JyF2mrCBnhuH6Hf6QeNDIQ==,type:str]
kind: ENC[AES256_GCM,data:voeZ+Pzi,iv:IH1px+wEWRpeSonwquH+0PJjatVXIoryIAIc/n1Otto=,tag:TIYXzL0ulmMt+/jF/f6HUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DT/8KWSO8CgypL44IC4loZZI,iv:guKmosTQbva9hiBxEQPmWlb2e6vu56pMKsrEnFAJiC4=,tag:R/ANcCeN7ZrXKkHf4TYJYg==,type:str]
    namespace: ENC[AES256_GCM,data:XaPiZvAW,iv:Zc/GUBvWZbXzXybndIlo4dX96dhJyfTXKDCKDNY/T9Q=,tag:J7giNPMnkU/tKELkJbUvNg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:d6a6MM8o,iv:NGHES+vzoJVIQFaMtpgXvMgqo1voQ/p6S3GgmfbG5RY=,tag:0GteQQ6AL6FBc7r4pgRBYA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:s/kCGBZKc75U/A==,iv:Gf2o8ag0DZ7zBYbWOEED0TElDkpu7y/bK7sghbwmBa0=,tag:X2lZ6ZavD71QWpNpjjpnJw==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:5/BuWYJ+RKUFgpumMjaCkg==,iv:xLxPUbMPVqNlpB7q8olRLwSpKr0DOj1Z5w5LGsCmNJ4=,tag:f3lN/g7k9SqjooikQvX4tw==,type:str]
type: ENC[AES256_GCM,data:ouvaTKUS,iv:WnoAc/zZ3G5r4IR2PZ9zGHrW/Iz0TL0IuiDpT3F0wGg=,tag:m1+xvQdRFGIjnMiw1mVOfg==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:RdfwlEK1uazwOwvBF+QBL28kPTghmZ3I9ZFFetw16FSAL10GOGpLv5fVmVxr/dua,iv:qr3Ku78WCmlGaXB016zMlyZFmyW6BgjK2h+gXEUhb9c=,tag:vyXrJgi4OpyaclN/nVxW3g==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeGhNWEFlVEFQOUpyOGZY
            OXo3NUxaK2xuMVA2aTF1d0xLdDgvVlpmb0JBCjByakRxYzE2MnQ5MWh6RWpwNE5H
            Y0pNSXhNS1NKOTkrMGZrQWkyc1J6REUKLS0tIFRrMTU1V3l1OTZSTXlQQkV3a0Yr
            bEVlemFSRThYSTVZNXNLVnRucENDUmsKeEnCsRNXYfpfJ24T7Os/zmNTNW+z/mk7
            QFNsmFvBTrO8LWeslY6pPxKEkF4Smo1Ol/8UHld5k9HMyW3BA3+TOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:18:05Z"
    mac: ENC[AES256_GCM,data:o3RMDcf30eAc1Xb+rL6qSEKcOQN3eFCAgNhQhhaHJqR7omFRCcsLHkom81NhSWrKuH3U2vI2W8AXZRme+weAslwUGc86ZkDgKE+oxexwN9PG9olB2iTPbSm6y/4bqlhop1vfOd5nZea706wT2tvyawLWCYtiPbN5Bx58Nemgszs=,iv:y6Cdr8WluBCR5pyXQSziSho0kiXknpwQwK0dtB23cxw=,tag:zXs/b7zRL961jFf9/zf1pA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
