apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cleanroom-db
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:williamdemarigny/Talos-CleanRoom.git
    targetRevision: refactor/restructure
    path: apps/cleanroom-db
    directory:
      recurse: false
      exclude: '{application.yaml,*.sops.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: cleanroom-db
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
