#ENC[AES256_GCM,data:mhW5iNRvN1Bn64MsNP+Xm2wtW8/f0UPqnRPjRly/9A==,iv:xBLDc4nHxzU00kZZYOP2oD64fZexTQtCk+0FXFpRro8=,tag:/qX0g6LSj1WDhJtU9wFpDg==,type:comment]
#ENC[AES256_GCM,data:1aodfAijj0KzndH/nFyIsjQR/srOfwrlkNU+/u/o06Mfb298yin7CS5oMDEZCVxhUWfwyhWIJsIk1hfR+A==,iv:mDaM3wnYFjG2zGZQuY2dJkHTdYFhVFYr/NFOHSoDSCY=,tag:YYrt0lmYqnfXbK0ZTLx5NQ==,type:comment]
#ENC[AES256_GCM,data:PoIXGHG43oxuHxrFiRxsEscYHSY/P4UOGJCs1xPtzWN6xC4aQcVhROUdZTnBCkQMShL+vC2emKBeJQvIXpch4t149w==,iv:T11/90LQuBikVA2F0g+7MK8rth8sI7e3gNVdBi2DAQo=,tag:EAFJEoC65J3nPxV0eiPJ3w==,type:comment]
apiVersion: ENC[AES256_GCM,data:hwo=,iv:haKg9XHFelaV48+2aLBtoojbmvLbvWSQXt8U+NG4+PM=,tag:infr4h5kedT7YPElJQgOLA==,type:str]
kind: ENC[AES256_GCM,data:JYF8RXHy,iv:ZsoAcwOXD2pPHdsBRirMY6xss4EN1+SPjD9ioEIOvhE=,tag:Q5YrJJ6EU+ZJrwkP5utE/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ri/B7S0f+j0Yer6loVeUdgwiIb3aXCq9,iv:p4wQKEMcWXrOL5c1B4v3MdFi02TvvidF02R+FNPVUMk=,tag:DdPnLGQDul57M7PjwIHwpA==,type:str]
    namespace: ENC[AES256_GCM,data:wkET98/Qa8f6sCwc,iv:6fwpF+4NB+OD1DTxPKUGimLWSZeWBC4wIPOf9Z2UHJE=,tag:/+AOz/X8BV5Kt5kVci3YJQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:xPz41bl5dG8D/80f,iv:UEjiyVAFrQTWiF80K65GC++KQP2PhjYgYp59e3YpcFY=,tag:j5Bte3gI78TrXEPMakXD/w==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:xD6QbYCziBg=,iv:PdieAnqS/QQPYpNgrrWnZ11mwplkOWz6pfz/0DkU0PA=,tag:ml3dSEkINyUgYjOUkl1YLg==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:Ql07kxIHomezIrdIbp7L6A==,iv:hnfd7rUJhIaKLQlWXAbsoPqLj71R+JnjzoCsik/O4/g=,tag:aBFM+YuxWkqwp4HRag1p4Q==,type:str]
type: ENC[AES256_GCM,data:U1LYABod,iv:f1JvhrYCoD+l6mEI2FqDB5aY6nCXVjjwbL8VHD5iEQc=,tag:pOo44vm1tZqobtyX0aFxHQ==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:F2fd6Eb0FLckX2CMwsq9+pag2I41n3Wl,iv:4i4PiXnpMnuIxE07ztzvH21fjYEtvRWFa30Ew22v5YA=,tag:6th37KDMDJ7guqTvD+WL4A==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOUtiamY2OGxZcDhkYkdE
            cTljdE5qQ3BlVnh5YVByaGxWdXh3eEgrMGljCm12NmxkQWd1cjZrWU5ZSkptSDdB
            dzZqMWQvbFJHMjd3aTVONG5oSWZtZzAKLS0tIGloRVU4Z25UV1FJZ1lSbU45L3k0
            T1VjVnZKL003NkZQT3hsRi9yYUNaODAKaL+Ce5hFubbLYG81fIJvtpalPy6IE8jf
            8AWm+PntFV1VJANOEoCCB4Zxs3hlv4/S6KLWVhK0rljLEVSZfCYsPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T20:34:39Z"
    mac: ENC[AES256_GCM,data:Avl32G2l+DEWciAZeKKXfAO+TZ8PNN+oBv1T2QtUhgJDeRQGFxTSQoVnye4T20ck580fnmzTQn24fMzxzNoHD2fjtlohne0+Z32zdexGpN601syqkGfgOjp9YW9vuR+w6HFrIg6x96IH1XUdsy8r5y0j+UPS+jbSdt5vhwusBZk=,iv:UdmwvhyU/IEOrcXerBC8NdhLCyw9Mp4HkNW3wwzaJ2I=,tag:Y2JCaqM+uv/li6nWZEMy4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
