#ENC[AES256_GCM,data:9sNBojf18AAvtMbGvFgaKYMMmT7HzyZ0GHWNuLQF6Q==,iv:lQjiZdcxe0dqHMrUPKja0DPVclrSLm4TRrSnTkqveAA=,tag:03zX1h/Ly4H2/bpPiZSSRQ==,type:comment]
#ENC[AES256_GCM,data:luhzte/qeEmcU2OlzM0cxGtqZKejSBuZ5iqEJeSg98oU/+aSaPMn84QiMWwzUZIeYTlXL9JrHk9K20arNA==,iv:yW4Fh3oJ9C/FIgGuizMzC8ij5V5CDPtNG3UrOnZKf6w=,tag:t8I3hpAvHfzFhQKxyMVAEw==,type:comment]
#ENC[AES256_GCM,data:ZbIY9YbF1POCY96fK756KJgfwQwmb+V78YOpQflzLkRB6s7ecEuJUiXuvfXNALBr4EiP+ai+4G7Yw7n555pW0hMHNw==,iv:ZG3ad/vDuS3alGHptvlHqQoDoZsF3WgCy/Hj6woL+3w=,tag:fIJVHhaa8/LCU4ppk7BKGg==,type:comment]
apiVersion: ENC[AES256_GCM,data:9r8=,iv:T5hQ+Nt32MkKvlqqF209qOkOjqf88w11odxy5EYpwG4=,tag:EloOLzAfiyZngYVHrHpV7w==,type:str]
kind: ENC[AES256_GCM,data:kY6f01p6,iv:jQxaiWgz9exzLsh7lpH7bpgynbzcgtPSPqmvVZJlXVs=,tag:gqj5s4gcShq2wshjYDQ8PQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qJEnSK84CSoKEbMslZJ6gpbnxKmkjrUm,iv:n/BVWkp9WgLNgBmG61GS1Fc0Bl+qIa4g2qFurQW2QnA=,tag:RcP/Vabe50v7HWge7Mh71g==,type:str]
    namespace: ENC[AES256_GCM,data:dd5X4mavQw1S3dAn,iv:yJPr1WsiLOyJFrRP+AyCJLkm1D8uAFm8dnXm+3Kzww0=,tag:vUNPjtK6uqXjoDO8Nnswrw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:gq4+Kd9Hfn3jCCzw,iv:lLYEiUzf7IzzLWUJeOA2kW0mFOhwLubUMEq206qXJrE=,tag:MIQBtqoigmOLXQw8HNFBrA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:weE621A9tFs=,iv:j4Y5O5hwKRVDk1aZK5OXZgLVbBuSzul+/YH+ldWN9p4=,tag:ACgXospGnmF0RQYMuxyS0w==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:2/7xF9YHKM4bsVvKa9T3Xg==,iv:8L/LxkFh27eRL7HR3qnULauzIRCHIp5QLhkngDsBzjs=,tag:8Bx4sp1e74NgQE3Nyi2atA==,type:str]
type: ENC[AES256_GCM,data:bYEhcLmP,iv:MSG74m+8HZ2H11TMiyhfItOEngno/DBgKmUtTFsVuE8=,tag:ERFExr7KhDX+GcXPTgkB3w==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:LTodd1TsKhrXlyXbI4MvveglBPAvGJje,iv:KTozlHw1XmBFEpxQF4GC1NRJj9maxzoGZ/cWnW+RCGw=,tag:shGEyEfjZ8U44ohvF2a4dw==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobm1qMU0rRHNtTExDS3Nx
            SnlIU1RSTE1wNzBZZzVFLzBKVFNTaWNjTHpZClIvVFAxVlNsVXJOdG1TS0JPM2to
            a2hCalVqbXpGT0Y5ZEZLM29qVUs4UTgKLS0tIDJMUloweFJ1czUxdXpGcFhveTBa
            MmJoT3FvaHJBa1UvYVgvbEs0aFlTUlEKeE6BoWBkaWm7DQib0oNXUBbkZ9mwpaSs
            fWlrG8jlJ1efajL3Olg3dZBgatjid2QsqaSurjze4SNb1LEBheEmGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T13:03:49Z"
    mac: ENC[AES256_GCM,data:jRi79RohnN/8QhKWUxfHUSiVQWdIqeyYjtDl/LrY9Zizi1VHnslFwFeII89dXkroxMYnPOyjS4L+fqRsek9DmgLiKQDPBd/lg7LJwW5K62JKx8qp9VntVHNYiAWKZGBf4lfymvAKFuGIhCxRPSUZnmfzLAOZ3wlK96hO7QLaz3Q=,iv:DCQ3jmoYCMR3XeNHxGWqBvZsNDE6r/oqh+dn3jtabi8=,tag:+eg08Pgei3tLAS6yZrAI3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
