#ENC[AES256_GCM,data:K2dvm9Iaa/GUoBAyBZVp6omuL2J8JoHCXe0nwN/jsg==,iv:/cUfTUFpni3woz6iCZMWFaCu/pG/V0eX6uMPPUgOkRQ=,tag:Ix3NpOVd4qHVAHpypMeERQ==,type:comment]
#ENC[AES256_GCM,data:bfc/hRP9SzzxuIFYgTx30wLEcnCpshJnmy5Vc6Ph1QuCcGM7p0x+esAp962UskmuF7YjUJ8LMGuGR5D0CQ==,iv:WPGocH0h+fXEaGWEQyyMCBjpLbX61HoISsYDCx0Wh1s=,tag:dAJL74HbKE0f2Xo3uS66pg==,type:comment]
#ENC[AES256_GCM,data:gevPGjznmfQl2LCKsA8cL1S0v+JiM+Q5tC8lJ3i/PtrKgxaut9Y5BflsczpdRSddz+1zzfnbf8oWXKz3aEEs3qTffQ==,iv:7/i+kT0FBfQuciTo/sB+acRMYksdwOznm7STI8HeVE4=,tag:ngFKVgkyczTRmFxsnKmTbA==,type:comment]
apiVersion: ENC[AES256_GCM,data:gvo=,iv:kBqNBXsZLPV0AJ0Y1t9ktg6nZZFtpORKbbWAF3Hx5u8=,tag:1Xtq6XkVLMKpUHXq9n3yZQ==,type:str]
kind: ENC[AES256_GCM,data:mIgIv0zh,iv:FSIUZm54AnuSYvBm3kseQonDqEKULILxqOBwUKdlnCE=,tag:BL86tqjtREuy3ZCPH0NY3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bcQyd1SdgkkxG3rSt+bmrcXfZFKdNHAt,iv:EMw3ZyQ6TB9BB2waAVm5BQUj7Yr5HIdfmkhu3JxVR8M=,tag:LYYLHs95xp0qxCdz2Y641A==,type:str]
    namespace: ENC[AES256_GCM,data:+ruOcGAXFGZPge4C,iv:5kqtVxJ++nqLh2nAH+PZdUEcT3h5RdDFfjA3EsILC+A=,tag:jlj+yyuDkNBTSnirjeY1ow==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:PfHq8iwPNjKJBbGq,iv:e5I3+GZfABWvJAkriefZt6slv81sOhvN92fi2YLWbBM=,tag:T9N6APHV/dsXXJqqGRUJJQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:x956fUn5nbA=,iv:/G9ha1GC3hYYl6dTvDi3WTBFYfb3gXmmbkCTS+bIMDM=,tag:HCNnORIbwTQYLNFrSw4mrQ==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:/oVEbPapWRCZXhJ7EMgYeQ==,iv:32AHPHRtqbqH5iUafABbH245IoR6qwLk0vi/OPmGUFw=,tag:NEa5oEFDmt0cVffCEdPcxg==,type:str]
type: ENC[AES256_GCM,data:skcMD+lZ,iv:UUt6DnW8eBOcTncPebCXNpI5SFYz+S+J4zHRQ4/Dn44=,tag:ZFc+TGEcfyClawRVaps3FQ==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:AcvLHWqHseblah+2nqkjsxD8DvYCzLlP,iv:WccseDolJKJ1U7s4Fo1zxo2T4ECp6AfbvG9V1bMQgTg=,tag:PZcboxDSt7XJlMIqk1SY8g==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXp1cG8vYmdva2cydW5X
            bldOTXg5Z1I3QkVsczZRd29kS2F6L0swSEFrCk5xRVAwMnY5a3lab2pEdHlSRGkr
            TUxnRThqaXJkQXV3SXpsNzdtZEtzSGMKLS0tIDc5cDNGRzlTb3djYTZPUEZMY2lQ
            TDNCTVBjTlVQTlB1SGJrQjQ3SEZrSk0KyXyFMIicez8qDocFdGJD5hz4xTdunDRI
            m+ndKsd6Gu84pOLgzSbB4VqzDvJXtnRhBcPeD9mC9jo0hc+o4uGIZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T22:42:03Z"
    mac: ENC[AES256_GCM,data:xltoV9PGon1Fc3JxbqsaRYxHKpS3AOi/WCGL0J3/FF5iI74VOr/WgCcKdD8Ktfi2BUlEPaJQ2GbhewUREDi25VBKGR1Q0aVuPg3ZOaDkGVBhQBATAE2E1dmO0R/bcqrTdCD/62fz5DCQMEv8DSkiKcnQDq2JM2n3oDeiQGbmDBU=,iv:Pow3dQLcJ+g/NSL+iktP5OWMl9Y/qQFE9R/lJGMjZio=,tag:0OUH242h2JG7VYJ8vxh07A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
