#!/bin/bash
# Talos CleanRoom Deployment Web UI - LXC Deployment Script
# Deploys the web UI as an LXC container on Proxmox
#
# Usage: ./deploy-lxc.sh

set -eo pipefail

# Configuration - Edit these values
PROXMOX_HOST="pve01.knowledgeondemand.net"
PROXMOX_API_URL="https://${PROXMOX_HOST}:8006"

# LXC Container Settings
LXC_VMID=200
LXC_HOSTNAME="deployment-webui"
LXC_IP="10.83.3.190/24"          # Adjust to your network
LXC_GATEWAY="10.83.3.1"          # Adjust to your gateway
LXC_CORES=2
LXC_MEMORY=2048
LXC_DISK=20
LXC_STORAGE="local-lvm"
NETWORK_BRIDGE="vmbr0"
VLAN_ID=3                        # Set to 0 for no VLAN

# DNS Settings
DNS_DOMAIN="knowledgeondemand.net"
DNS_SERVERS='["8.8.8.8", "8.8.4.4"]'

# Web UI Settings
WEBUI_USER="admin"
WEBUI_PASSWORD="admin"           # Change this!

# GitHub SSH Settings (for private repository access)
GITHUB_SSH_KEY=""                # Path to SSH private key for GitHub
GITHUB_REPO_URL="git@github.com:williamdemarigny/Talos-CleanRoom.git"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}"
echo "============================================"
echo "Talos CleanRoom Deployment Web UI"
echo "LXC Container Deployment"
echo "============================================"
echo -e "${NC}"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="${SCRIPT_DIR}/terraform"

# Check for terraform
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: terraform is not installed${NC}"
    exit 1
fi

# Prompt for credentials if not set
if [ -z "$PROXMOX_API_TOKEN" ]; then
    echo -e "${YELLOW}Enter Proxmox API Token (format: user@pam!tokenid=secret):${NC}"
    read -r PROXMOX_API_TOKEN
fi

if [ -z "$PROXMOX_SSH_PASSWORD" ]; then
    echo -e "${YELLOW}Enter Proxmox SSH password for root:${NC}"
    read -rs PROXMOX_SSH_PASSWORD
    echo ""
fi

if [ -z "$LXC_ROOT_PASSWORD" ]; then
    echo -e "${YELLOW}Enter password for LXC container root user:${NC}"
    read -rs LXC_ROOT_PASSWORD
    echo ""
fi

# Prompt for GitHub SSH key
if [ -z "$GITHUB_SSH_KEY" ]; then
    # Check common SSH key locations
    DEFAULT_KEY=""
    for key_path in ~/.ssh/id_ed25519 ~/.ssh/id_rsa ~/.ssh/github ~/.ssh/id_ecdsa; do
        if [ -f "$key_path" ]; then
            DEFAULT_KEY="$key_path"
            break
        fi
    done

    if [ -n "$DEFAULT_KEY" ]; then
        echo -e "${YELLOW}Enter path to GitHub SSH private key [${DEFAULT_KEY}]:${NC}"
        read -r GITHUB_SSH_KEY
        GITHUB_SSH_KEY="${GITHUB_SSH_KEY:-$DEFAULT_KEY}"
    else
        echo -e "${YELLOW}Enter path to GitHub SSH private key:${NC}"
        read -r GITHUB_SSH_KEY
    fi
fi

# Validate SSH key exists
if [ ! -f "$GITHUB_SSH_KEY" ]; then
    echo -e "${RED}Error: SSH key not found at ${GITHUB_SSH_KEY}${NC}"
    exit 1
fi

echo -e "${GREEN}  Using SSH key: ${GITHUB_SSH_KEY}${NC}"

# Download LXC template to Proxmox if needed
echo -e "${GREEN}[1/5] Checking LXC template on Proxmox...${NC}"

TEMPLATE_NAME="debian-12-standard_12.12-1_amd64.tar.zst"
TEMPLATE_STORAGE="cephfs"

# SSH options for automated connections (accept new host keys, don't save to known_hosts)
SSH_OPTS="-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null"

# Check if template exists via SSH
echo "  Checking if template exists on Proxmox..."
TEMPLATE_EXISTS=$(ssh ${SSH_OPTS} -o ConnectTimeout=10 root@${PROXMOX_HOST} \
    "pveam list ${TEMPLATE_STORAGE} 2>/dev/null | grep -c '${TEMPLATE_NAME}'" 2>/dev/null || echo "0")

if [ "$TEMPLATE_EXISTS" = "0" ]; then
    echo -e "${YELLOW}  Template not found. Downloading to Proxmox...${NC}"
    ssh ${SSH_OPTS} root@${PROXMOX_HOST} \
        "pveam download ${TEMPLATE_STORAGE} ${TEMPLATE_NAME}" || {
        echo -e "${RED}  Failed to download template automatically.${NC}"
        echo -e "${YELLOW}  Please download manually on Proxmox:${NC}"
        echo "    pveam download ${TEMPLATE_STORAGE} ${TEMPLATE_NAME}"
        echo ""
        read -p "Press Enter once template is downloaded, or Ctrl+C to cancel..."
    }
else
    echo -e "${GREEN}  Template already exists on Proxmox${NC}"
fi

# Create terraform.tfvars
echo -e "${GREEN}[2/5] Creating Terraform configuration...${NC}"

cat > "${TERRAFORM_DIR}/terraform.tfvars" << EOF
# Auto-generated by deploy-lxc.sh on $(date)

# Proxmox Connection
proxmox_api_url      = "${PROXMOX_API_URL}"
proxmox_api_token    = "${PROXMOX_API_TOKEN}"
proxmox_ssh_user     = "root"
proxmox_ssh_password = "${PROXMOX_SSH_PASSWORD}"
proxmox_node         = ""
proxmox_pool         = ""

# LXC Container Configuration
lxc_vmid      = ${LXC_VMID}
lxc_hostname  = "${LXC_HOSTNAME}"
lxc_cores     = ${LXC_CORES}
lxc_memory    = ${LXC_MEMORY}
lxc_swap      = 512
lxc_disk_size = ${LXC_DISK}
lxc_storage   = "${LXC_STORAGE}"
lxc_tags      = ["deployment", "webui", "management"]

# Template Configuration (downloaded via pveam in step 1)
template_storage      = "cephfs"
lxc_template_filename = "${TEMPLATE_NAME}"

# Network Configuration
network_bridge  = "${NETWORK_BRIDGE}"
vlan_id         = ${VLAN_ID}
lxc_ip_address  = "${LXC_IP}"
lxc_gateway     = "${LXC_GATEWAY}"
lxc_mac_address = ""

# DNS Configuration
dns_domain  = "${DNS_DOMAIN}"
dns_servers = ${DNS_SERVERS}

# Authentication
lxc_root_password = "${LXC_ROOT_PASSWORD}"
ssh_public_keys   = []

# Web UI Configuration
webui_admin_username = "${WEBUI_USER}"
webui_admin_password = "${WEBUI_PASSWORD}"
EOF

echo "  Configuration written to ${TERRAFORM_DIR}/terraform.tfvars"

# Initialize Terraform
echo -e "${GREEN}[3/5] Initializing Terraform...${NC}"
cd "${TERRAFORM_DIR}"
terraform init

# Plan deployment
echo -e "${GREEN}[4/5] Planning deployment...${NC}"
terraform plan -out=.tfplan

# Confirm deployment
echo ""
echo -e "${YELLOW}Ready to deploy LXC container with the following settings:${NC}"
echo "  Proxmox Host: ${PROXMOX_HOST}"
echo "  Container ID: ${LXC_VMID}"
echo "  Hostname:     ${LXC_HOSTNAME}"
echo "  IP Address:   ${LXC_IP}"
echo "  Resources:    ${LXC_CORES} cores, ${LXC_MEMORY}MB RAM, ${LXC_DISK}GB disk"
echo ""
read -p "Proceed with deployment? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

# Apply deployment
echo -e "${GREEN}[5/5] Deploying LXC container...${NC}"
terraform apply .tfplan

# Get container IP (strip CIDR notation)
CONTAINER_IP="${LXC_IP%/*}"

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}LXC Container Deployed Successfully!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "Container IP: ${CONTAINER_IP}"
echo ""
echo -e "${YELLOW}Next Steps (Manual Setup):${NC}"
echo ""
echo "1. Copy SSH key to container (from your workstation):"
echo "   scp ${GITHUB_SSH_KEY} root@${CONTAINER_IP}:/root/.ssh/github_deploy_key"
echo ""
echo "2. SSH into the container:"
echo "   ssh root@${CONTAINER_IP}"
echo ""
echo "3. Configure SSH for GitHub access:"
echo "   chmod 600 /root/.ssh/github_deploy_key"
echo "   cat > /root/.ssh/config << 'EOF'"
echo "   Host github.com"
echo "       HostName github.com"
echo "       User git"
echo "       IdentityFile /root/.ssh/github_deploy_key"
echo "       IdentitiesOnly yes"
echo "       StrictHostKeyChecking accept-new"
echo "   EOF"
echo "   chmod 600 /root/.ssh/config"
echo ""
echo "4. Clone the repository:"
echo "   git clone ${GITHUB_REPO_URL} /opt/Talos-CleanRoom"
echo ""
echo "5. Run the setup script:"
echo "   cd /opt/Talos-CleanRoom/deployment-webui/scripts"
echo "   chmod +x setup-lxc.sh"
echo "   ./setup-lxc.sh --webui-password ${WEBUI_PASSWORD}"
echo ""
echo "6. Copy SOPS keys (from your workstation):"
echo "   ssh root@${CONTAINER_IP} \"mkdir -p /root/.config/sops/age\""
echo "   scp ~/.config/sops/age/keys.txt root@${CONTAINER_IP}:/root/.config/sops/age/"
echo ""
echo "7. Start the web UI service:"
echo "   systemctl start deployment-webui"
echo ""
echo "8. Access the web UI:"
echo "   http://${CONTAINER_IP}:8000"
echo ""
echo "   Login: ${WEBUI_USER} / ${WEBUI_PASSWORD}"
echo ""
echo -e "${GREEN}============================================${NC}"

# Optional: Run setup automatically
echo ""
read -p "Run setup script automatically via SSH? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Remove any old host keys for this IP (container may have been recreated)
    echo -e "${GREEN}Clearing old SSH host keys for ${CONTAINER_IP}...${NC}"
    ssh-keygen -R "${CONTAINER_IP}" 2>/dev/null || true

    echo -e "${GREEN}Waiting for container to be ready...${NC}"

    # Wait for SSH to become available (max 120 seconds)
    MAX_WAIT=120
    WAIT_INTERVAL=5
    ELAPSED=0

    while [ $ELAPSED -lt $MAX_WAIT ]; do
        if ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5 root@${CONTAINER_IP} "exit" 2>/dev/null; then
            echo -e "${GREEN}  SSH is available after ${ELAPSED} seconds${NC}"
            break
        fi
        echo "  Waiting for SSH... (${ELAPSED}/${MAX_WAIT}s)"
        sleep $WAIT_INTERVAL
        ELAPSED=$((ELAPSED + WAIT_INTERVAL))
    done

    if [ $ELAPSED -ge $MAX_WAIT ]; then
        echo -e "${RED}Error: Timed out waiting for SSH to become available${NC}"
        echo -e "${YELLOW}Troubleshooting:${NC}"
        echo "  1. Check container is running: ssh root@${PROXMOX_HOST} 'pct status ${LXC_VMID}'"
        echo "  2. Check network from Proxmox: ssh root@${PROXMOX_HOST} 'pct enter ${LXC_VMID}' then 'ip addr'"
        echo "  3. Verify VLAN ${VLAN_ID} is reachable from your workstation"
        echo ""
        echo "You can run the manual setup steps printed above once connectivity is resolved."
        exit 1
    fi

    # Read the GitHub SSH key content for transfer
    GITHUB_SSH_KEY_CONTENT=$(cat "${GITHUB_SSH_KEY}")

    echo -e "${GREEN}Copying SSH key and running full setup (single SSH session)...${NC}"
    echo -e "${YELLOW}Enter password once - all setup will run automatically${NC}"

    ssh -o StrictHostKeyChecking=accept-new root@${CONTAINER_IP} << ENDSSH
set -e

echo "=== Setting up SSH key for GitHub ==="
mkdir -p /root/.ssh && chmod 700 /root/.ssh

cat > /root/.ssh/github_deploy_key << 'KEYEOF'
${GITHUB_SSH_KEY_CONTENT}
KEYEOF
chmod 600 /root/.ssh/github_deploy_key

cat > /root/.ssh/config << 'SSHCONFIG'
Host github.com
    HostName github.com
    User git
    IdentityFile /root/.ssh/github_deploy_key
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
SSHCONFIG
chmod 600 /root/.ssh/config

echo "=== Installing git ==="
apt-get update && apt-get install -y git

echo "=== Testing GitHub SSH connectivity ==="
ssh -T git@github.com 2>&1 || true

echo "=== Cloning repository ==="
git clone ${GITHUB_REPO_URL} /opt/Talos-CleanRoom

echo "=== Running setup script ==="
cd /opt/Talos-CleanRoom/deployment-webui/scripts
chmod +x setup-lxc.sh
./setup-lxc.sh --webui-password "${WEBUI_PASSWORD}"

echo "=== Starting web UI service ==="
systemctl start deployment-webui
systemctl status deployment-webui --no-pager
ENDSSH

    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}Setup Complete!${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    echo "Web UI is now running at: http://${CONTAINER_IP}:8000"
    echo ""
    echo "Don't forget to copy your SOPS keys:"
    echo "  ssh root@${CONTAINER_IP} \"mkdir -p /root/.config/sops/age\""
    echo "  scp ~/.config/sops/age/keys.txt root@${CONTAINER_IP}:/root/.config/sops/age/"
    echo ""
fi
