#ENC[AES256_GCM,data:FtUWw9hevzSk6PSAt/FhAMz2Rku1mmNyh1r+PEbL,iv:RJG8jsJ0CchW5TW8vkJtNaxoXZC4mLh6dPurDGey0qY=,tag:l7+iM2Bcnlnym84+p9VHJQ==,type:comment]
#ENC[AES256_GCM,data:tBkz8C6AvhyGdnVOeYO544S+SsVcxt9IqrV5WQFa,iv:rP/D3yBPUEpgGdgHNP5nIm/H91apETiRIcF/AhWRQuA=,tag:emcy6dhQNwTYzxX7DL2OQw==,type:comment]
#ENC[AES256_GCM,data:NKm6i54vhOpJvGc3NEOXosWog9i5nXpIjpi0vrS6ZcOSySMuWEBRUlmyYSzZOEFdkOVATl26ioMXzSHckiU8ReL2ufW1iCj81WM+rfiED1gUoydDd30qzXhF5dyw8Bal,iv:DbIAw0zzOvXGl0Cusc2ya5q3uG61Qq8Yxj3+v+h3V/E=,tag:k2/pjnxKFtkqDebgdPYSmA==,type:comment]
#ENC[AES256_GCM,data:rgS9uq8MjGaXpPE4uci4ESF1R2FqSmoq4pW3VdLH/nOtcItnb+f1sd0BrrSRkHSdBG5hpRfet0TUScai/m35QqIzgNtL95W05S1th/YEW/2yHI/qBf247Su2Hr/bGXp72dT38wFsde/nKKUmkGMuulRpOVEBkg==,iv:FANLgZ3LB7nSY6yxnsR1fwBvkhfIf8XP4vTa6oweQ90=,tag:Xxugsf4EwXHdBLqvRPo9KA==,type:comment]
#ENC[AES256_GCM,data:OZU4EAhezjTr7UbaOjW0K+vmHlOa4EoVlCpshnNnAQ8tr5qQXqit1JByvNhqNO7OanXb,iv:PZSmX015F4v32TQDkMpdHgfWM/y6xzoSGtLSStDZHpU=,tag:BLmnm8JmVEPuEiGCEBPPhg==,type:comment]
apiVersion: ENC[AES256_GCM,data:NLs=,iv:4eNFDENEJyMDkDF24rDLi6506A+7Z/cxw8PV8YvXK2E=,tag:knVrky24htMYRXZHfIea/Q==,type:str]
kind: ENC[AES256_GCM,data:riwVPYUc,iv:ds3n8U0ImxNJQLZhIBekIU6tqanCzcBe9vM3ktCSg2g=,tag:3jDSWnaMhEDe+wC+4L+N9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rHL8nTP2+kxqT4i7rNPXY+k=,iv:3yvBKcvvmnh6xICyEkPZuWoEgMwzzsLxbJMpGQWZ//8=,tag:aDjlgQ0Cf+eVPWOf6h++VA==,type:str]
    namespace: ENC[AES256_GCM,data:Y9VI5dZF,iv:ff8O+4uX2MWgtQWY1Rq4qoiZb2P2fEdIqnS/miHrWkI=,tag:gILZDIi93sSDlgeRETcN1Q==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:RXj1pCj//NlGOw==,iv:vDgv+KoZrHM7+NooygmZyDA6ZF3D+toEB8dUUf+l0Wg=,tag:pabyHoguo2Wru3i94SONhQ==,type:str]
type: ENC[AES256_GCM,data:rbq1+M0X,iv:fAvWlFVeBSq2FkdAol5q1BU24qZiT7rW/Pf/iakWHi0=,tag:nfqL8v8L3wjEmwYlyuY11g==,type:str]
stringData:
    type: ENC[AES256_GCM,data:MYzP,iv:IVLhyE3idvmibcQ1Zzkmykm3d17/cI7AMhOYucp+tb0=,tag:j0hztej6h8Z7YLlKG5p7cA==,type:str]
    url: ENC[AES256_GCM,data:fE96ahZ0gkQUFmME6aW1Le7NhQpxjJ9sqIW/2dUfE5MpxdochrOe+FnhsIvg7oTUKfjN,iv:AERiU7Dr9r8Wj/t+AucQJR6ZmZrbUXeC7ZJ4wM9CYEM=,tag:LDI+/pdlA5vynL0WLmfZdA==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:In9F4fay8lX8XJW+CocRkhQymc24ltDOAcOe73JeEgqc7Bu0iN7Vu5JyM5S7/OyZpY353cyCMFuXj+VU8w8cjlzFDUToeEUXFGMPg37Ikpl0WOf38H6ADmpbgIWeWF1dZMVIYqbFPuWCvrcLLvX2QbaaG4Tr8UIUpL6ppuU68wOY21njHvIgbXUsyuIo4BKKYwVjZ/G/MkDATmn+342X3M7D6JBEL4fvdFlt8LIrMnHkRH2H5uVPA/ABEHNoP1+2nAfvQXyeNllHKiS9dySgyGcLM2qz7RX1r357ay3bRROXg183vsoZk9n0KKtUFax3EjUhiStGoAgE1A+RwjcaGfY9Euh+bi1dE03h0e7DX/qUE1t3S607QiWEXQbLrf8qj+10Qf4CSyZ/yJui1Pdywr0cNewxr09eQ91C9xLQPsK/lD3hamcJbZHYVu5XkMbebNT9+9MwCEoDWejYrrFYgB+mFivEpFktw63+FSNaxhqiunUMQjxT0BUABba/UR2MtgdW/fMdaB1ENM0MC26tvl3Ul7drjw47mLWq,iv:A71HwCwTlzWrzLviDUeb5fwlm4r9ZhhYZrDbfqQxgWU=,tag:6DML1ciVjJ0VEcpcqKYHRw==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbVhCQUo0My8wa2tabUhM
            R1BYTFFidTlSN3BiQTBzN3pqamdibHN6WndNCnF4S3NmNlBqVjNaNmlKd3JobXFM
            STg3ekpNK3lRbTZRenJnSDY3VEZkNjgKLS0tIEZTUUtoUTdIa1lOVW5DQktRZC9n
            dTJCMkROMkh2ZERydHVoK055MzZEV0UKQeTKB1+EPWt91OXHk8uqsKJ8JSchkgQl
            /woUNI7zYFjFeJxfK9wdQuR/VEOqyJoVA1nRvAW/B5a2tC+bIzJxhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T19:43:41Z"
    mac: ENC[AES256_GCM,data:NLSpcgSO8Upop63Rcjj1bQslAxmTPd5knckl7dLhsHkLDMaPN8lwjyq/JKjrHHIEeXnZJVs0HMaNXtBuSp4kciDWjyE9sdlins+MEUPwGHNejG1gcFXl83r1uN60XNpEYF/s1ev1aL3ak3fXrDxuuUlEJau/ydCfNkJaG/bifZ0=,iv:86UGM+FjEEu9H6m4swaB1T1wamjdk6XeK7AO3w7Hon0=,tag:E4hgWemAJ+W8+9Oz4uJHEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
