#ENC[AES256_GCM,data:cdf4+QyFY1vmDaQUuXaBZHFyWE86wnND/A==,iv:46kIW8VAXY8pjMnrY3aCArHr1xAhurfEc9eJOZ++0jw=,tag:/h/6f53JUaAzUaNCDPDW9A==,type:comment]
#ENC[AES256_GCM,data:cpQCJdg42FiTL7zdwNFlDtZyhtiFgqIN26ryU+DczuwwnnHTsQAXMuIJgY80zeN4qBwiUV/XqK3mcEGamw==,iv:gHJ2G8M/F16WF7oWjyCUDQATw5mManIgS/Ya+p54NwE=,tag:7ys+52py5P9QeZgsHwCnBQ==,type:comment]
#ENC[AES256_GCM,data:dkHjL2CCF3P9nRPZUO3xUBd1kmURV0rc58TctZ+zXvY=,iv:ovmX6jW+hkgTZ1Xhwqgmxb0Gc8kpNSv5C0U5S//11Bw=,tag:jp9V1j4ZFx42QgWEHeo/MA==,type:comment]
apiVersion: ENC[AES256_GCM,data:ViA=,iv:ophpfWojeYo/6UUR/GgNoQ3XCYPy+7Zrg7Supx3Rusc=,tag:OVau636X8WSuIWSCeY8skA==,type:str]
kind: ENC[AES256_GCM,data:K0zeYfan,iv:ASAtzEf7QnSlmOgwV3dxq+y0cSb0IzVVeGmdPrN/eHI=,tag:9+2jYkQlLiJn2UPcZvyc+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:D3UMh33j4rFqv0Q3uLLxQ10AprxkRw==,iv:MuitkBq1AEFQmKJvPZGqDSlMPBFLlE6k7uSywv30pTA=,tag:59FT996wQsal166RhH8prg==,type:str]
    namespace: ENC[AES256_GCM,data:z3sTI5PV,iv:zCzr71o0GWWtt9bS7T9qjyIA/ZIwKIvavdd1/zx4Quw=,tag:FT1ooKKfhe3AdIEu0gSb6A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:Qlp1+qJA,iv:h2yVl7zYJXKo0iKd5eyEfbx8+U1m7ISfSH2DYAL4VUA=,tag:I5+48P9vLvOYT2uDEcZZDA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:UZJoS+Dx,iv:onSY6LQjYvypa4/Pt2CH5NoK59iCMr6njNtMghUNFg8=,tag:r11LWQgNrmK8bsksVfE0ng==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:WY+HNQsDWGOW16AeemZcuQ==,iv:gADh9TgXIrGt5bHgBiTv3vOpCTtVdlybjjYyzACSNbI=,tag:kyPaXu/aAe9hVdrkB2gtOg==,type:str]
type: ENC[AES256_GCM,data:F02x4ZwX,iv:l7kXkmLBUB4J0/YOI8ZhaXDzKqkDvHCty0T7o09TVaQ=,tag:hYACIR5zO+eOMROG0hoXwQ==,type:str]
stringData:
    admin.password: ENC[AES256_GCM,data:bog4kwtn23f+BrAkxxun2Ixg2YOwSo7+pgrk/3aoLt0U3VyFH7AVEkoHv2ZWBViOG+NkMTjPrLns7tLx,iv:SRUMv1qXrWkXp/J0ET3t09RteyTe3Uo04CV41qnqxIY=,tag:uOA8xD29X01d3oz7LQcfFA==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:Lqe9I2YGlAqScIgyyTjy9IHVP04=,iv:5m2pfNbpi6dTeL/9Yv7g3hmfz5aXKU5qpPUiuFA0j/E=,tag:uVYSTRpLSQuwsjXVVrEXiQ==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NmxzK0lvMjFGZm5FU3FI
            UUlXR3VIeW5PYnNmdlZCazU4WnJMM3R3Q2lvCms1UHlzWUdyajNMVnNwNGpwS25Z
            eGVqdVl3WXdkdmtjU1BjWXFwYXIva00KLS0tIFkyMEl3N2VncGFYNTNwc1h6Q1Na
            Q1hVcldjL1RPTExUYzZWSThTSG5qa1UKXRpT36sCmAQcEDeqa9eIlzQ/1kkK9A7u
            vbMGBhfv4lPvUEXjio4k2+vAYGetsBDTQ+x/zQ/7DDd+iwZ7TWrdkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T13:03:49Z"
    mac: ENC[AES256_GCM,data:ofwnnbejf10FeZ9RlCfvklPYcbaCeA1rVTPyrTNwrd47OFLy8xNzIWctYt3YkvEc8dJWSHiHKkAK/LQVlsNYkRSMSfIUMAiLfRI/ZOw1SFciG0NuHZ+D+urwodUiL1NUopm6kCP8QAiHCn4MyrYdU0WEILAqFjiwsxIC0s4rXDA=,iv:aVmFhpzOnYOJYIl+abVIsGr3AEhIoEByjzYEuuyhNbk=,tag:KwsJUhF2xiLW36IkTWlGKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
