#ENC[AES256_GCM,data:jvwi/qXZa3hp8pSiEK9OxmBsKDc9OUeYyA==,iv:zs3f4V3MR5vrXoQwp+bFNt4ktdv/tJZQJp8a9FfEc3A=,tag:8YnlpAO8d/m+z7ld3GONcQ==,type:comment]
#ENC[AES256_GCM,data:Rh5NQ77HBeRaZiM4ho1GSBiMRWIZtaGvI6EELg9CP5ii+yott8iWJ7c3p48vQvUQBzDnnO8cUwbhZnzswA==,iv:X5S3YDh6SWUBnglACw1GeyMQuN9mk0O6l3dGTtScc4g=,tag:THlfeqf5Wvg5rjDtfCo0vA==,type:comment]
#ENC[AES256_GCM,data:HDGGvYHmYWNeA+nO/AHhFdR+VUkHs7gvj/h35yqKne0=,iv:zD7GIWhnf5o8lJwstyVBw6GC/GlPEQYYuUQKZgMYXIc=,tag:tLHQNW0ezJ9xHPWez1ETGQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:tYY=,iv:AeeDCx6ANJD0F9kB+tPAk6d4AxSk9AnjkWY4TUSh5A0=,tag:b8vKfCFv3uGeQBO1gm7oyQ==,type:str]
kind: ENC[AES256_GCM,data:aa2YLYJ5,iv:anCLoFeaOTbWaBjk81ku2O0dWrGoDGwfhOGRiO6cCoo=,tag:mk/mL1EK6s1cJCHWZwXvUQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TSBV7t0kkjVp8eTOH+N24emwU0cBtQ==,iv:T9lUB0sigdSjVSN+KYhJ2KK7TuJI8EURoALKHK1u3WE=,tag:IqX7FVLSKgR7CqCloO0WGA==,type:str]
    namespace: ENC[AES256_GCM,data:sChZY12G,iv:9tbzh2S56cvOq9bcBkWTE+WBzDb70qTRdi7Vh4Xhwuo=,tag:OqiUAiH0TnfywC5/W1xMeA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:LaFS5BZ+,iv:gnqRYewlS58J+1+kTRbpmw5AnfTdDZWuUXvBiVUQXCM=,tag:cko/CMrcXYkosn7oxCCZCg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:SUDSUOIG,iv:FElZcz2BdGWcSgnvwGLeVfHEO0ImnliNutQrSfv6m3A=,tag:1BcYQYA1iolvRxPIUJxpXg==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:J2m/vld+FF09wlzihTYo6w==,iv:ulR9/Of4DdE86uOXR80cL7CA59gRq46TUVLOOUdrfE4=,tag:gSu9tert/T2QApPKG4sXvg==,type:str]
type: ENC[AES256_GCM,data:P1MGlbjV,iv:wg8i7Cv+4+d6ed8NeEZzLzhARAkNnSmwuA73GhfjF3s=,tag:r9QmSciWlBIlAuhk8sMKPg==,type:str]
stringData:
    admin.password: ENC[AES256_GCM,data:otVM4seEVsdIRwz45hQGxs8GJvTiYUQznvR2lfXgNpTrTR5x8kGmm6SWfINUtiVtj/nIKoGyo8yWkH/D,iv:NUBKVYuDXdJFX6g6009+DVaOl8sg2WBsrZ7ZnvAFUH8=,tag:mGEeO5HqzjXwEdNknsjHNg==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:XQkwdQikmwPsNnp2f61mr4uk9Yg=,iv:CqoKkoV1Yvf0EdeUm++xkhKwMurju3iMQ1brzYn16sM=,tag:qe/os0iKTaoLDDA8nB2qXA==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a0tIWkpYcUJ5UjRwU3dT
            V1JOdi82MFJhcUovSVU2dlZLaldzLzdwcVdVCmJ0YTBFVVAzeHRYUC8zaFhVTkI1
            NURKaVhYVllUM3VYZnA1cTR3dU9pWjQKLS0tICt2NW1veE5JeDBSRGV2aENsaTh5
            WEk3SnRtcWUzYTBmU1VNRnRJU2diVncKvZ9syjyPPx75+aAwLaYu4D67NhJAutxc
            Ry5uIi36F5BtXQ3j838UV/fzlCId4QasaQu3JMEtt0a00i+Wo0PL4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T15:18:04Z"
    mac: ENC[AES256_GCM,data:jsZILolJ/QDkyrKyMdHREmv9pe2H/i2Td27GPoFe5WgA5+u8wrF+4rP8PLcUqs5EyAUUkENgHEm9NsbRMo/kYb+i17NfOQmZBS+l1IsSfdkDkuNFf7QqHuA6hy85igQcbl7LostNz3bFEbqGoiK7sz+j50VRBAkafFeoWQE/208=,iv:+/Uh/EicKvVOPilSq2czX+hQxG15YHniEwYJkFjAU+w=,tag:4aID4utvQORPrCz+EMeKVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
