#ENC[AES256_GCM,data:AyWroPVeSWlg6Wj6yQPGDOP6jqMYSRGU7Q==,iv:phTDBd8LW1cT4hG5vF7O9FF+95Uc9pOtfrteUQ5nmT0=,tag:CprqcP0/QqwLo8Mu6iPGYw==,type:comment]
#ENC[AES256_GCM,data:8zCifJXfqZXuH1fxTGD3JTHSUmD0bNyU0/D9iKVGfHyTkc/aXYxlaa3AKX8kPb5HAcnXWrTrNRmZU7D0Rg==,iv:M+WospyaoDQb+nQAY9/H8csJ8XtLVICn6iCO8CmLB0Q=,tag:B580YV3TBxdImsXpiZUHqw==,type:comment]
#ENC[AES256_GCM,data:yRuKQKY/1OPfeR4VRpqkrl2itTLZ3rJcCHs6FPzMmoc=,iv:udACuX3akLEt0wHVWQwrfgBVZa1my6835KAupVcYKc8=,tag:jgmktObuuxpqe3mSpi7QjA==,type:comment]
apiVersion: ENC[AES256_GCM,data:q+o=,iv:Z0xncOFD7C1DO2M6xrDrp4c6WrxOSKyc2b9iOdBJDk4=,tag:MDkvzTGfdK477PsiFqeGIQ==,type:str]
kind: ENC[AES256_GCM,data:LaTUDQpv,iv:a6C3ZDONQxyqvQRuDAZNh3jEASiKwunCqDH73UOlcfo=,tag:OpH73UciLOLZBgYcLI+VEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dhSNxhjJ+pNhuG61Kv1ukFhPlh4w6g==,iv:qd4r2Dz0OJ1ejtW+w2vVa+GtU8MceNCM8Ng0+LWhurU=,tag:2VcHJF3Km6AweQzbYJYhMQ==,type:str]
    namespace: ENC[AES256_GCM,data:+bKzyyES,iv:wvoMSF95wDaRuYn509WjqNj/prGJIvn/7muhVh666hE=,tag:bTQO7oVBhuo7wsD76ZQb5A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:tCQe+j9j,iv:6CR8JHRbGudY8qymQrpQsFYfck/k9oHZafeS2b6zvxg=,tag:fYexH5oOg0NUgK4qCY4EyA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:/parUseJ,iv:d7h1xG306TArv+nswDBgbFPZAs7AyWUiJYABKBoKzIY=,tag:y1y3WCm6XW4e2hIq/aqmjw==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:rDeaUIxxhunOifLCBQnoRA==,iv:FDSM9WQdVU8pE4BFQqQa/003C2V7ESg6ai9UsN4OYnU=,tag:OvW/Cz3+/osF0R3r8Fw60w==,type:str]
type: ENC[AES256_GCM,data:mWv1H6+I,iv:xgbgRy5Hhiukc1qnyWZ1ZU4J8GFXMpn8OZ4fIpRyhLw=,tag:jZS6dHc137FZQfmx451sMg==,type:str]
stringData:
    admin.password: ENC[AES256_GCM,data:t5uRKqHYJm5mIiZuFAd4MlMJqDL2A7nBezbZWoMlhCWaANTq81U++Q71l9SYRilLKpsCol7oJx+hdSlg,iv:6hBFTrGW1ivlVcoW9rsZcoeLsuPhygU8ee5W2T2lHP4=,tag:569IwjJy8CSZpAVoPhPiCA==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:cYi9NJPGib0quMXrpFLFiQ3B428=,iv:9MFj63jOVDAsTRQMWY5qMJuFeiKbUUNeIlgxG+Sr+w4=,tag:Un7b7JQSICzglryb6czjvA==,type:str]
sops:
    age:
        - recipient: age1hdskklcj78alg00z80u6r5cgm9w5fcg33y0n064kss33ugmqca5q9zcerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZWVZMEpnbDg2RVVZa2JG
            Y0czd3VEU1VualN0NHZjcUdBelJTWjV4bVVjCjd3akZiNTRkY0R5VG1QYWRwYlVM
            L28wRCs0SzFBM2ZiTFNiMlBQck5CR0UKLS0tIE5HOFZvTnVRaUJBTUVXRlMwZ294
            Q29BZGhqSUVGQUw3K3pYMm9TS213K1EK9mwvXEFYoRh350KovrWbh2ZRh5GQBc4l
            BTpv4Tteka5/7iTCbRLyYj2ciC3H2G1q7nOkjIy4eveZlDebA0Ub8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:52:38Z"
    mac: ENC[AES256_GCM,data:R8pOC93glaV+hsHZp1rV/ZQhrEEtMM2aNlm2VWJ8J7pwB1skWY3F1TJdFtX+yeDyzm++kqpz/WWl+RZeLzn24jjENFvkKy4TNyuQrWqDR8kLUTmakNfTFCQuTtdm5aRly8CG/kNuvQVHW18+Qz8A9mr/ztWg6w6Rls6FhpGsezg=,iv:xOg4DcDt3h8O7CJw7qAAJ4R6I4ix8JdoMtJ/TKUN0Gk=,tag:9H2Z7w4jHLEewtpraYau0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
