"""One-time code exchange endpoint for cross-domain authentication.

The target app (Scanning Console or Deployment Console) includes this
router to accept opaque codes generated by the Portal and mint a new
local JWT in return.  See docs/vuln-management-plan.md Appendix A.

Usage:
    from talos_common.routers.exchange import router as exchange_router
    app.include_router(exchange_router, prefix="/api/auth")
"""

import hashlib
import hmac
import time

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

import talos_common
from talos_common.auth import create_access_token

router = APIRouter()


class RedeemRequest(BaseModel):
    """Request body for redeeming a one-time auth code."""
    code: str


class RedeemResponse(BaseModel):
    """Response after successfully redeeming a code."""
    access_token: str
    token_type: str = "bearer"


@router.post("/redeem-code", response_model=RedeemResponse)
async def redeem_code(request: RedeemRequest):
    """Redeem a one-time code for a JWT access token.

    The code format is ``<random>:<exp>:<username>:<signature>`` where
    the signature is HMAC-SHA256 over ``<random>:<exp>:<username>``
    using the derived ``code_exchange_key``.

    The target app verifies the HMAC and expiry, then mints a **new**
    JWT for the extracted username (it does NOT receive the portal's JWT).
    """
    settings = talos_common.get_settings()

    try:
        parts = request.code.split(":")
        if len(parts) != 4:
            raise HTTPException(403, "Invalid code format")
        code, exp_str, username, signature = parts

        # Verify HMAC with derived key (same SECRET_KEY -> same derived key)
        sign_payload = f"{code}:{exp_str}:{username}".encode()
        expected = hmac.new(
            settings.code_exchange_key.encode(), sign_payload, hashlib.sha256
        ).hexdigest()
        if not hmac.compare_digest(signature, expected):
            raise HTTPException(403, "Invalid code")

        # Check expiry
        if time.time() > int(exp_str):
            raise HTTPException(403, "Code expired")

        # Mint a NEW JWT for this app (do NOT reuse the portal's JWT)
        access_token = create_access_token(username, settings)
        return RedeemResponse(access_token=access_token)

    except HTTPException:
        raise
    except Exception:
        raise HTTPException(403, "Invalid code")
